standford robot PATH CALCULATOR

In [ ]:
'''x(t) = ax0 + ax1t + ax2t^2 + ax3t^3
y(t) = ay0 + ay1t + ay2t^2 + ay3t^3
z(t) = az0 + az1t + az2t^2 + az3t^3
dot.x(t) =  ax1 + 2*ax2t + 3*ax3t^2
dot.y(t) =  ay1 + 2*ay2t + 3*ay3t^2
dot.z(t) =  az1 + 2*az2t + 3*az3t^2

p(0) = p0
p(tf ) = pf
˙p(0) = 0
˙p(tf )=0'''
import numpy as np
import scipy
ini=np.array([1,1,1])
f=np.array([3,3,3])
tf=7
ax0=ini[0]
ay0=ini[1]
az0=ini[2]
ax1=0
ay1=0
az1=0
'''
ax2*tf**2 + ax3*tf**3=f[0]
ay2*tf**2 + ay3*tf**3=f[1]
az2*tf**2 + az3*tf**3=f[2]
2*ax2*tf + 3*ax3*tf**2=0
2*ay2*tf + 3*ay3*tf**2=0
2*az2*tf + 3*az3*tf**2=0'''
#X=np.array([ax2,ax3,ay2,ay3,az2,az3])
A=np.array([[tf**2,tf**3,0,0,0,0],[0,0,tf**2,tf**3,0,0],[0,0,0,0,tf**2,tf**3],[2*tf,3*tf**2,0,0,0,0],[0,0,2*tf,3*tf**2,0,0],[0,0,0,0,2*tf,3*tf**2]])
K=np.array([f[0],f[1],f[2],0,0,0])
invA=np.linalg.inv(A)
X=invA@K
print(X);
ax2=X[0]
ax3=X[1]
ay2=X[2]
ay3=X[3]
az2=X[4]
az3=X[5]
Aa=np.array([[ax0,ax1,ax2,ax3],[ay0,ay1,ay2,ay3],[az0,az1,az2,az3]])
arr = np.array([[1,2,3],[4,5,6]])

#PATH calculator
def pathfunc(tf,Aa,arr):
  t=0
  for t in range (tf+1):
    T=np.array([1,t,t**2,t**3])
    print(t)
    
    row=Aa@T
    print(row)
    arr = np.vstack([arr,row])

  return arr

arr = np.array([[0,0,0]])
arr1 =pathfunc(tf,Aa,arr) #here we get all the points of trajectory
print(arr1)

#inverse kinematics

def invkine(arr1,J):
  for i in range(len(arr1)):
    x=[0]*3;
    x=arr1[i];
    offset=2;
    d1=3;
    d2=1;
    r = abs((x[0]**2+x[1]**2-d1**2-d2**2)/(2*d1*d2))
    theta2 = np.arctan(np.sqrt(abs(1-r**2))/r)
    theta1 = np.arctan(x[1]/x[0]) - np.arctan((d2*np.sin(theta2))/(d1+d2*np.cos(theta2)))
    d3 =offset-x[2]
    s=np.array([theta1,theta2,d3])
    J=np.vstack([J,s])
  return J

    
J=np.array([[0,0,0]])
arr2=invkine(arr1,J) #here we get all the JOINT VAR of trajectory
print(arr2)


[ 0.18367347 -0.01749271  0.18367347 -0.01749271  0.18367347 -0.01749271]
0
[1. 1. 1.]
1
[1.16618076 1.16618076 1.16618076]
2
[1.59475219 1.59475219 1.59475219]
3
[2.18075802 2.18075802 2.18075802]
4
[2.81924198 2.81924198 2.81924198]
5
[3.40524781 3.40524781 3.40524781]
6
[3.83381924 3.83381924 3.83381924]
7
[4. 4. 4.]
[[0.         0.         0.        ]
 [1.         1.         1.        ]
 [1.16618076 1.16618076 1.16618076]
 [1.59475219 1.59475219 1.59475219]
 [2.18075802 2.18075802 2.18075802]
 [2.81924198 2.81924198 2.81924198]
 [3.40524781 3.40524781 3.40524781]
 [3.83381924 3.83381924 3.83381924]
 [4.         4.         4.        ]]
[[ 0.          0.          0.        ]
 [        nan  0.67474094  2.        ]
 [ 0.6424904   0.5843739   1.        ]
 [ 0.65874639  0.51530277  0.83381924]
 [ 0.63623502  0.61126651  0.40524781]
 [ 0.47257178  1.48927457 -0.18075802]
 [ 0.73894073  0.18623433 -0.81924198]
 [ 0.60972479  0.72758217 -1.40524781]
 [ 0.60245313  0.76026321 -1.83381924]
 [

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:73: RuntimeWarning: invalid value encountered in double_scalars


In [ ]:
arr2[:,2]

array([ 0.        ,  2.        ,  1.        ,  0.83381924,  0.40524781,
       -0.18075802, -0.81924198, -1.40524781, -1.83381924, -2.        ])

In [ ]:
import sympy as sym
from sympy import diff, sin, cos
from scipy.integrate import odeint
import scipy
import scipy.integrate
from scipy.integrate import solve_ivp
import numpy as np
import matplotlib.pyplot as plt
a=10.333333333333332 
b=7.666666666666666 
g=6 
d=1.3333333333333333
GR=9.8
m4=1



sym.init_printing()
q1, q2, d4,q1dot,q2dot,d4dot,q1ddot,q2ddot,d4ddot,T1,T2,F,mG,l1,l2 = sym.symbols('q1 q2 d4 q1dot q2dot d4dot q1ddot q2ddot d4ddot T1 T2 F mG l1 l2')
k1=sym.Matrix([q1,q2,d4])
k2=sym.Matrix([q1dot,q2dot,d4dot])
k3=sym.Matrix([q1ddot,q2ddot,d4ddot])
GQ=sym.Matrix([0,0,mG])
tau=sym.Matrix([T1,T2,F])
M=sym.Matrix([[-(l1/2)*sym.sin(q1),0,0],[(l1/2)*sym.cos(q1),0,0],[0,0,0]]);
X=M.T
N=sym.Matrix([[-l1*sym.sin(q1)-(l2/2)*sym.sin(q1+q2),-(l2/2)*sym.sin(q1+q2),0],[(l1)*sym.cos(q1)+(l2/2)*sym.cos(q1+q2),(l2/2)*sym.cos(q1+q2),0],[0,0,0]]);
Y=N.T
O=sym.Matrix([[-l1*sym.sin(q1)-(l2)*sym.sin(q1+q2),-(l2)*sym.sin(q1+q2),0],[(l1)*sym.cos(q1)+(l2)*sym.cos(q1+q2),(l2)*sym.cos(q1+q2),0],[0,0,-1]]);

A1=sym.Matrix([[sym.cos(q1),0,-sym.sin(q1),0],[sym.sin(q1),0,sym.cos(q1),0],[0,-1,0,l1],[0,0,0,1]]);
A2=sym.Matrix([[sym.cos(q2),0,sym.sin(q2),0],[sym.sin(q2),0,-sym.cos(q2),0],[0,1,0,l2],[0,0,0,1]]);
A3=sym.Matrix([[1,0,0,0],[0,1,0,0],[0,0,1,d4],[0,0,0,1]]);


sym.simplify(A1*A2*A3)
#sym.simplify(Z1.cross(O3)),sym.simplify(Z2)

⎡cos(q₁)⋅cos(q₂)  -sin(q₁)  sin(q₂)⋅cos(q₁)  d₄⋅sin(q₂)⋅cos(q₁) - l₂⋅sin(q₁)⎤
⎢                                                                           ⎥
⎢sin(q₁)⋅cos(q₂)  cos(q₁)   sin(q₁)⋅sin(q₂)  d₄⋅sin(q₁)⋅sin(q₂) + l₂⋅cos(q₁)⎥
⎢                                                                           ⎥
⎢   -sin(q₂)         0          cos(q₂)              d₄⋅cos(q₂) + l₁        ⎥
⎢                                                                           ⎥
⎣       0            0             0                        1               ⎦

In [ ]:

sym.simplify(A1*A2)

⎡cos(q₁)⋅cos(q₂)  -sin(q₁)  sin(q₂)⋅cos(q₁)  -l₂⋅sin(q₁)⎤
⎢                                                       ⎥
⎢sin(q₁)⋅cos(q₂)  cos(q₁)   sin(q₁)⋅sin(q₂)  l₂⋅cos(q₁) ⎥
⎢                                                       ⎥
⎢   -sin(q₂)         0          cos(q₂)          l₁     ⎥
⎢                                                       ⎥
⎣       0            0             0              1     ⎦

In [ ]:

sym.simplify(A1)

⎡cos(q₁)  0   -sin(q₁)  0 ⎤
⎢                         ⎥
⎢sin(q₁)  0   cos(q₁)   0 ⎥
⎢                         ⎥
⎢   0     -1     0      l₁⎥
⎢                         ⎥
⎣   0     0      0      1 ⎦

here we calculated Z0 Z1 Z2 O3,O2,O1,O0

NOW WE CALCULATE THE SYMBOLIC JACOBIAN

In [ ]:
import sympy as sym
from sympy import diff, sin, cos
from scipy.integrate import odeint
import scipy
import scipy.integrate
from scipy.integrate import solve_ivp
import numpy as np
import matplotlib.pyplot as plt
a=10.333333333333332 
b=7.666666666666666 
g=6 
d=1.3333333333333333
GR=9.8
m4=1



sym.init_printing()
q1, q2, d4,q1dot,q2dot,d4dot,q1ddot,q2ddot,d4ddot,T1,T2,F,mG,l1,l2 = sym.symbols('q1 q2 d4 q1dot q2dot d4dot q1ddot q2ddot d4ddot T1 T2 F mG l1 l2')
k1=sym.Matrix([q1,q2,d4])
k2=sym.Matrix([q1dot,q2dot,d4dot])
k3=sym.Matrix([q1ddot,q2ddot,d4ddot])
GQ=sym.Matrix([0,0,mG])
tau=sym.Matrix([T1,T2,F])
M=sym.Matrix([[-(l1/2)*sym.sin(q1),0,0],[(l1/2)*sym.cos(q1),0,0],[0,0,0]]);
X=M.T
N=sym.Matrix([[-l1*sym.sin(q1)-(l2/2)*sym.sin(q1+q2),-(l2/2)*sym.sin(q1+q2),0],[(l1)*sym.cos(q1)+(l2/2)*sym.cos(q1+q2),(l2/2)*sym.cos(q1+q2),0],[0,0,0]]);
Y=N.T
O=sym.Matrix([[-l1*sym.sin(q1)-(l2)*sym.sin(q1+q2),-(l2)*sym.sin(q1+q2),0],[(l1)*sym.cos(q1)+(l2)*sym.cos(q1+q2),(l2)*sym.cos(q1+q2),0],[0,0,-1]]);

Z0=sym.Matrix([[0],[0],[1]]);
Z1=sym.Matrix([[-sym.sin(q1)],[sym.cos(q1)],[0]]);
Z2=sym.Matrix([[sym.cos(q1)*sym.sin(q2)],[sym.sin(q1)*sym.sin(q2)],[sym.cos(q2)]]);
O3=sym.Matrix([[sym.cos(q1)*sym.sin(q2)*d4-sym.sin(q1)*l2],[sym.sin(q1)*sym.sin(q2)*d4+sym.cos(q1)*l2],[sym.cos(q2)*d4+l1]])
O2=sym.Matrix([[sym.sin(q2)*sym.cos(q1)],[sym.sin(q1)*sym.sin(q2)],[sym.cos(q2)]])
O1=sym.Matrix([[-l2*sym.sin(q1)],[l2*sym.cos(q1)],[l1]])

O0=sym.Matrix([[0],[0],[0]])

sym.simplify(Z0.cross(O3-O0)),sym.simplify(Z1.cross(O3-O1)),sym.simplify(Z2)

#DQ=sym.simplify(X*M)+sym.simplify(Y*N)+sym.simplify(Z*O)

⎛⎡-d₄⋅sin(q₁)⋅sin(q₂) - l₂⋅cos(q₁)⎤  ⎡d₄⋅cos(q₁)⋅cos(q₂)⎤  ⎡sin(q₂)⋅cos(q₁)⎤⎞
⎜⎢                                ⎥  ⎢                  ⎥  ⎢               ⎥⎟
⎜⎢d₄⋅sin(q₂)⋅cos(q₁) - l₂⋅sin(q₁) ⎥, ⎢d₄⋅sin(q₁)⋅cos(q₂)⎥, ⎢sin(q₁)⋅sin(q₂)⎥⎟
⎜⎢                                ⎥  ⎢                  ⎥  ⎢               ⎥⎟
⎝⎣               0                ⎦  ⎣   -d₄⋅sin(q₂)    ⎦  ⎣    cos(q₂)    ⎦⎠

AFTER CALCULATING JACOBIAN WE CALCULATE THE KINETIC + ROTATIONAL ENERGY AND HENCE THE DQ AND CQ matrix and GQ matrix

In [2]:
import sympy as sym
from sympy import diff, sin, cos
from scipy.integrate import odeint
import scipy
import scipy.integrate
from scipy.integrate import solve_ivp
import numpy as np
import matplotlib.pyplot as plt

m1g=1
m2g=1
m3g=1
i1=1
i2=1
GR=9.8
m4=1
l1=2
l2=2
#I1 0
#0 I2

sym.init_printing()
q1, q2, d4,q1dot,q2dot,d4dot,q1ddot,q2ddot,d4ddot,T1,T2,F,mG= sym.symbols('q1 q2 d4 q1dot q2dot d4dot q1ddot q2ddot d4ddot T1 T2 F mG ')
k1=sym.Matrix([q1,q2,d4])
k2=sym.Matrix([q1dot,q2dot,d4dot])
k3=sym.Matrix([q1ddot,q2ddot,d4ddot])

VQ=m1g*l1/2+m2g*(l1+l2/2)*sym.sin(q1)+m3g*(l1+l2/2+d4/2)*sym.sin(q1)
X1=sym.diff(VQ,q1)
X2=sym.diff(VQ,q2)
X3=sym.diff(VQ,d4)
GQ=sym.Matrix([X1,X2,X3])

tau=sym.Matrix([T1,T2,F])
#FOR KINETIC ENERGY CALCULATION
M=sym.Matrix([[-l2*sym.cos(q1),l1*sym.cos(q1),0],[-l2*sym.sin(q1),l1*sym.sin(q1),0],[0,0,1]]);
X=M.T
N=sym.Matrix([[-l2*sym.cos(q1),l1*sym.cos(q1),sym.sin(q2)*sym.cos(q1)],[-l2*sym.sin(q1),l1*sym.sin(q1),sym.sin(q1)*sym.sin(q2)],[0,0,sym.cos(q2)]]);
Y=N.T
O=sym.Matrix([[-d4*sym.sin(q1)*sym.sin(q2)-l2*sym.cos(q1),(d4*sym.cos(q2)+l1)*sym.cos(q1),sym.sin(q2)*sym.cos(q1)],[d4*sym.sin(q1)*sym.cos(q2)-l2*sym.sin(q1),(d4*sym.cos(q2)+l1)*sym.sin(q1),sym.sin(q1)*sym.sin(q2)],[0,-d4*sym.sin(q2),sym.cos(q2)]]);
Z=O.T
I=sym.Matrix([[i1,0,0],[0,i2,0],[0,0,0]])
#FOR ROTATIONAL ENERGY CALCULATION
M1=sym.Matrix([[-sym.sin(q1),0,0],[sym.cos(q1),0,0],[0,1,0]]);
X1=M1.T
N1=sym.Matrix([[-sym.sin(q1),sym.cos(q1)*sym.sin(q2),0],[sym.cos(q1),sym.sin(q1)*sym.sin(q2),0],[0,sym.cos(q2),0]]);
Y1=N1.T


DQ0=sym.simplify(X*M)+sym.simplify(Y*N)+sym.simplify(Z*O)
DQ1=(sym.simplify(X1*M1)+sym.simplify(Y1*N1))*I
DQ=DQ0+DQ1


no1=3

CQQD= sym.Matrix([[0,0,0],[0,0,0],[0,0,0]])

#Cqqd CALCULATOR
for k in range(no1):
    for j in range(no1):
        su=0
        for i in range(no1):
            su+=(0.5*(sym.diff(DQ[k,j],k1[i]) + sym.diff(DQ[k,i],k1[j])-sym.diff(DQ[i,j],k1[k])))*k2[i]
            
        CQQD[k,j]=su
        
        

difF=DQ.inv()*(CQQD*(k2)+GQ-tau)
difF

⎡                                                                             
⎢                                                                             
⎢                                                                             
⎢                                                           ──────────────────
⎢                                                             4    2        2 
⎢                                                           d₄ ⋅sin (q₁)⋅sin (
⎢                                                                             
⎢                                                    ⎛        ⎛   ⎛        2  
⎢                                                 ⎜-F + q1̇⋅⎝q1̇⋅⎝- d₄⋅sin (q₁
⎢                                                    ⎝                        
⎢             ────────────────────────────────────────────────────────────────
⎢               4    2        2        2                4    2        2       
⎢             d₄ ⋅sin (q₁)⋅sin (q₂)⋅sin (q₁ - q₂) + 

In [19]:
from sympy.printing.pycode import pycode
pycode(difF[2])

'(-F + q1dot*(q1dot*(-1.0*d4*math.sin(q1)**2 + 1.0*(d4*math.sin(q1)*math.cos(q1 - q2) + d4*math.sin(q1 - q2)*math.cos(q1))*math.sin(q2) + 2.0*math.sin(q1)*math.sin(q1 - q2)) + q2dot*(-0.5*d4*math.sin(q1)*math.sin(q2)*math.cos(q1 - q2) - 0.5*(d4*math.cos(q2) + 2)*math.sin(q1)*math.sin(q1 - q2) - 1.0*math.cos(q2))) + q2dot*(q1dot*(-0.5*d4*math.sin(q1)*math.sin(q2)*math.cos(q1 - q2) - 0.5*(d4*math.cos(q2) + 2)*math.sin(q1)*math.sin(q1 - q2) - 1.0*math.cos(q2)) + q2dot*(-1.0*d4 + 2.0*math.cos(q2))) + (1/2)*math.sin(q1))*(d4**4*math.sin(q1)**2*math.sin(q1 - q2)**2*math.cos(q2)**2 - d4**4*math.sin(q1)**2 + 4*d4**3*math.sin(q1)**2*math.sin(q1 - q2)**2*math.cos(q2) - 4*d4**3*math.sin(q1)**2*math.cos(q2) - 4*d4**3*math.sin(q1)*math.sin(q1 - q2)*math.cos(q2)**2 + 4*d4**3*math.sin(q1)*math.sin(q1 - q2) + 4*d4**2*math.sin(q1)**2*math.sin(q1 - q2)**2 - 14*d4**2*math.sin(q1)**2 - 16*d4**2*math.sin(q1)*math.sin(q1 - q2)*math.cos(q2) + 4*d4**2*math.cos(q2)**2 - 14*d4**2 + 8*d4*math.sin(q1)*math.sin(q1

FINAL SOLVER WITH PI IMPLEMENTATION

In [20]:
 import sympy as sym
 import math as math
 from sympy import diff, sin, cos
 from scipy.integrate import odeint
 import scipy
 import scipy.integrate
 from scipy.integrate import solve_ivp
 import numpy as np
 import matplotlib.pyplot as plt
'''def model(z,t):
  dq1dt=sym.diff(q1)
  dq2dt=sym.diff(q2)
  dzdt=sym.diff(d4)
  dq1ddt=r[0]
  dq2ddt=r[1]
  dzddt=r[2]
  dzdt=[dq1dt,dq2dt,dzdt,dq1ddt,dq2ddt,dzddt]
  return dzdt

z0 = [0,0]
t=np.linspace(0,5)
z=odeint(model,z0,t)'''
 E1=[]
 E2=[]
 E3=[]
 T=[]
 Q1=np.array([0.65874639, 0.63623502,
       0.47257178, 0.73894073, 0.60972479, 0.60245313, 0.60116773])
 Q2=np.array([0.51530277, 0.61126651,
       1.48927457, 0.18623433, 0.72758217, 0.76026321, 0.766080053])
 D4=np.array([0.83381924,  0.40524781,
       -0.18075802, -0.81924198, -1.40524781, -1.83381924, -2.])

 def Model(t, y):


    '''
    function for the ODE solver - returns dy/dt of states
    '''
    KP=0.5
    KI=0.2
    q1=y[0]
    q2=y[1]
    d4=y[2]
    q1dot=y[3]
    q2dot=y[4]
    d4dot=y[5]
    dq1dt=q1dot
    dq2dt=q2dot
    dzdt=d4dot
    
    T.append(t)
   
    n=round(t)
    if(t<=n+1):
      e1=(Q1[n-1]-q1)
      e2=(Q2[n-1]-q2)
      e3=(D4[n-1]-d4)
    else:
      n=n+1
      e1=(Q1[n]-q1)
      e2=(Q2[n]-q2)
      e3=(D4[n]-d4)
   
    E1.append(e1)
    E2.append(e2)
    E3.append(e3)
    s1=0
    s2=0
    s3=0

    if(t>2):
        for i in range(7):
            s1=s1+ (E1[-(1+i)])*(T[-(1+i)]-T[-(2+i)])
            s2=s2+ (E2[-(1+i)])*(T[-(1+i)]-T[-(2+i)])
            s3=s3+ (E3[-(1+i)])*(T[-(1+i)]-T[-(2+i)])

    T1=KP*(e1)+KI*(s1)
    #print(T1)
    T2=KP*(e2)+KI*(s2)
    F=KP*(e3)+KI*(s3)
   
    
    dq1ddt=(-F + q1dot*(q1dot*(-1.0*d4*math.sin(q1)**2 + 1.0*(d4*math.sin(q1)*math.cos(q1 - q2) + d4*math.sin(q1 - q2)*math.cos(q1))*math.sin(q2) + 2.0*math.sin(q1)*math.sin(q1 - q2)) + q2dot*(-0.5*d4*math.sin(q1)*math.sin(q2)*math.cos(q1 - q2) - 0.5*(d4*math.cos(q2) + 2)*math.sin(q1)*math.sin(q1 - q2) - 1.0*math.cos(q2))) + q2dot*(q1dot*(-0.5*d4*math.sin(q1)*math.sin(q2)*math.cos(q1 - q2) - 0.5*(d4*math.cos(q2) + 2)*math.sin(q1)*math.sin(q1 - q2) - 1.0*math.cos(q2)) + q2dot*(-1.0*d4 + 2.0*math.cos(q2))) + (1/2)*math.sin(q1))*(d4**3*math.sin(q1)*math.sin(q2)*math.sin(q1 - q2) - 4*d4**2*math.sin(q2) + 6*d4*math.sin(q1)*math.sin(q2)*math.sin(q1 - q2) - 8*d4*math.sin(q2)*math.cos(q2) - 8*math.sin(q2))/(d4**4*math.sin(q1)**2*math.sin(q2)**2*math.sin(q1 - q2)**2 + 3*d4**4*math.sin(q1)**2*math.sin(q1 - q2)**2*math.cos(q2)**2 - 3*d4**4*math.sin(q1)**2 - 4*d4**3*math.sin(q1)**2*math.sin(q2)**2*math.sin(q1 - q2)**2*math.cos(q2) + 12*d4**3*math.sin(q1)**2*math.sin(q1 - q2)**2*math.cos(q2) - 12*d4**3*math.sin(q1)**2*math.cos(q2) - 8*d4**3*math.sin(q1)*math.sin(q2)**2*math.sin(q1 - q2) - 12*d4**3*math.sin(q1)*math.sin(q1 - q2)*math.cos(q2)**2 + 12*d4**3*math.sin(q1)*math.sin(q1 - q2) - 2*d4**2*math.sin(q1)**2*math.sin(q2)**2*math.sin(q1 - q2)**2 + 16*d4**2*math.sin(q1)**2*math.sin(q2)**2 + 12*d4**2*math.sin(q1)**2*math.sin(q1 - q2)**2 - 42*d4**2*math.sin(q1)**2 + 16*d4**2*math.sin(q1)*math.sin(q2)**2*math.sin(q1 - q2)*math.cos(q2) - 48*d4**2*math.sin(q1)*math.sin(q1 - q2)*math.cos(q2) + 16*d4**2*math.sin(q2)**2 + 12*d4**2*math.cos(q2)**2 - 42*d4**2 - 16*d4*math.sin(q1)*math.sin(q2)**2*math.sin(q1 - q2) + 24*d4*math.sin(q1)*math.sin(q1 - q2) - 24*d4*math.cos(q2) + 64*math.sin(q2)**2 - 156) + (-T2 + d4dot*(q1dot*(0.5*d4*math.sin(q1)*math.sin(q2)*math.cos(q1 - q2) + 0.5*(d4*math.cos(q2) + 2)*math.sin(q1)*math.sin(q1 - q2) + 1.0*math.cos(q2)) + q2dot*(1.0*d4 + 2.0*math.cos(q2))) + q1dot*(d4dot*(0.5*d4*math.sin(q1)*math.sin(q2)*math.cos(q1 - q2) + 0.5*(d4*math.cos(q2) + 2)*math.sin(q1)*math.sin(q1 - q2) + 1.0*math.cos(q2)) + q1dot*(-2.0*d4*math.sin(q1)*math.cos(q1 - q2) + 1.0*(d4*math.cos(q2) + 2)*(d4*math.sin(q1)*math.cos(q1 - q2) + d4*math.sin(q1 - q2)*math.cos(q1)))) + q2dot*(-2.0*d4*q2dot*math.sin(q2) + d4dot*(1.0*d4 + 2.0*math.cos(q2))))*(3*d4**2*math.sin(q1)*math.sin(q1 - q2)*math.cos(q2) - 4*d4*math.sin(q1)*math.sin(q2)**2*math.sin(q1 - q2) + 6*d4*math.sin(q1)*math.sin(q1 - q2) - 6*d4*math.cos(q2) + 16*math.sin(q2)**2 - 36)/(d4**4*math.sin(q1)**2*math.sin(q2)**2*math.sin(q1 - q2)**2 + 3*d4**4*math.sin(q1)**2*math.sin(q1 - q2)**2*math.cos(q2)**2 - 3*d4**4*math.sin(q1)**2 - 4*d4**3*math.sin(q1)**2*math.sin(q2)**2*math.sin(q1 - q2)**2*math.cos(q2) + 12*d4**3*math.sin(q1)**2*math.sin(q1 - q2)**2*math.cos(q2) - 12*d4**3*math.sin(q1)**2*math.cos(q2) - 8*d4**3*math.sin(q1)*math.sin(q2)**2*math.sin(q1 - q2) - 12*d4**3*math.sin(q1)*math.sin(q1 - q2)*math.cos(q2)**2 + 12*d4**3*math.sin(q1)*math.sin(q1 - q2) - 2*d4**2*math.sin(q1)**2*math.sin(q2)**2*math.sin(q1 - q2)**2 + 16*d4**2*math.sin(q1)**2*math.sin(q2)**2 + 12*d4**2*math.sin(q1)**2*math.sin(q1 - q2)**2 - 42*d4**2*math.sin(q1)**2 + 16*d4**2*math.sin(q1)*math.sin(q2)**2*math.sin(q1 - q2)*math.cos(q2) - 48*d4**2*math.sin(q1)*math.sin(q1 - q2)*math.cos(q2) + 16*d4**2*math.sin(q2)**2 + 12*d4**2*math.cos(q2)**2 - 42*d4**2 - 16*d4*math.sin(q1)*math.sin(q2)**2*math.sin(q1 - q2) + 24*d4*math.sin(q1)*math.sin(q1 - q2) - 24*d4*math.cos(q2) + 64*math.sin(q2)**2 - 156) + (-3*d4**2 - 12*d4*math.cos(q2) + 16*math.sin(q2)**2 - 42)*(-T1 + d4dot*(1.0*d4dot*math.sin(q1)*math.sin(q2)*math.sin(q1 - q2) + q1dot*(1.0*d4*math.sin(q1)**2 - 2.0*math.sin(q1)*math.sin(q1 - q2)) + q2dot*(-0.5*d4*math.sin(q1)*math.sin(q2)*math.cos(q1 - q2) + 0.5*(d4*math.cos(q2) + 2)*math.sin(q1)*math.sin(q1 - q2) + 1.0*(d4*math.sin(q1)*math.sin(q1 - q2) - 2)*math.cos(q2) - 1.0*math.cos(q2))) + q1dot*(2.0*d4*q2dot*math.sin(q1)*math.cos(q1 - q2) + d4dot*(1.0*d4*math.sin(q1)**2 - 2.0*math.sin(q1)*math.sin(q1 - q2)) + q1dot*(1.0*d4**2*math.sin(q1)*math.cos(q1) - 2.0*d4*math.sin(q1)*math.cos(q1 - q2) - 2.0*d4*math.sin(q1 - q2)*math.cos(q1))) + q2dot*(2.0*d4*q1dot*math.sin(q1)*math.cos(q1 - q2) + d4dot*(-0.5*d4*math.sin(q1)*math.sin(q2)*math.cos(q1 - q2) + 0.5*(d4*math.cos(q2) + 2)*math.sin(q1)*math.sin(q1 - q2) + 1.0*(d4*math.sin(q1)*math.sin(q1 - q2) - 2)*math.cos(q2) - 1.0*math.cos(q2)) + q2dot*(-1.0*d4*(d4*math.cos(q2) + 2)*math.sin(q1)*math.cos(q1 - q2) - 1.0*d4*(d4*math.sin(q1)*math.sin(q1 - q2) - 2)*math.sin(q2))) + ((1/2)*d4 + 3.0)*math.cos(q1) + 3.0*math.cos(q1))/(d4**4*math.sin(q1)**2*math.sin(q2)**2*math.sin(q1 - q2)**2 + 3*d4**4*math.sin(q1)**2*math.sin(q1 - q2)**2*math.cos(q2)**2 - 3*d4**4*math.sin(q1)**2 - 4*d4**3*math.sin(q1)**2*math.sin(q2)**2*math.sin(q1 - q2)**2*math.cos(q2) + 12*d4**3*math.sin(q1)**2*math.sin(q1 - q2)**2*math.cos(q2) - 12*d4**3*math.sin(q1)**2*math.cos(q2) - 8*d4**3*math.sin(q1)*math.sin(q2)**2*math.sin(q1 - q2) - 12*d4**3*math.sin(q1)*math.sin(q1 - q2)*math.cos(q2)**2 + 12*d4**3*math.sin(q1)*math.sin(q1 - q2) - 2*d4**2*math.sin(q1)**2*math.sin(q2)**2*math.sin(q1 - q2)**2 + 16*d4**2*math.sin(q1)**2*math.sin(q2)**2 + 12*d4**2*math.sin(q1)**2*math.sin(q1 - q2)**2 - 42*d4**2*math.sin(q1)**2 + 16*d4**2*math.sin(q1)*math.sin(q2)**2*math.sin(q1 - q2)*math.cos(q2) - 48*d4**2*math.sin(q1)*math.sin(q1 - q2)*math.cos(q2) + 16*d4**2*math.sin(q2)**2 + 12*d4**2*math.cos(q2)**2 - 42*d4**2 - 16*d4*math.sin(q1)*math.sin(q2)**2*math.sin(q1 - q2) + 24*d4*math.sin(q1)*math.sin(q1 - q2) - 24*d4*math.cos(q2) + 64*math.sin(q2)**2 - 156)
    dq2ddt=(-F + q1dot*(q1dot*(-1.0*d4*math.sin(q1)**2 + 1.0*(d4*math.sin(q1)*math.cos(q1 - q2) + d4*math.sin(q1 - q2)*math.cos(q1))*math.sin(q2) + 2.0*math.sin(q1)*math.sin(q1 - q2)) + q2dot*(-0.5*d4*math.sin(q1)*math.sin(q2)*math.cos(q1 - q2) - 0.5*(d4*math.cos(q2) + 2)*math.sin(q1)*math.sin(q1 - q2) - 1.0*math.cos(q2))) + q2dot*(q1dot*(-0.5*d4*math.sin(q1)*math.sin(q2)*math.cos(q1 - q2) - 0.5*(d4*math.cos(q2) + 2)*math.sin(q1)*math.sin(q1 - q2) - 1.0*math.cos(q2)) + q2dot*(-1.0*d4 + 2.0*math.cos(q2))) + (1/2)*math.sin(q1))*(-d4**3*math.sin(q1)**2*math.sin(q2)*math.sin(q1 - q2)**2*math.cos(q2) - 2*d4**2*math.sin(q1)**2*math.sin(q2)*math.sin(q1 - q2)**2 + 4*d4**2*math.sin(q1)**2*math.sin(q2) + 6*d4**2*math.sin(q1)*math.sin(q2)*math.sin(q1 - q2)*math.cos(q2) + 4*d4*math.sin(q1)*math.sin(q2)*math.sin(q1 - q2) - 8*d4*math.sin(q2)*math.cos(q2) + 8*math.sin(q2))/(d4**4*math.sin(q1)**2*math.sin(q2)**2*math.sin(q1 - q2)**2 + 3*d4**4*math.sin(q1)**2*math.sin(q1 - q2)**2*math.cos(q2)**2 - 3*d4**4*math.sin(q1)**2 - 4*d4**3*math.sin(q1)**2*math.sin(q2)**2*math.sin(q1 - q2)**2*math.cos(q2) + 12*d4**3*math.sin(q1)**2*math.sin(q1 - q2)**2*math.cos(q2) - 12*d4**3*math.sin(q1)**2*math.cos(q2) - 8*d4**3*math.sin(q1)*math.sin(q2)**2*math.sin(q1 - q2) - 12*d4**3*math.sin(q1)*math.sin(q1 - q2)*math.cos(q2)**2 + 12*d4**3*math.sin(q1)*math.sin(q1 - q2) - 2*d4**2*math.sin(q1)**2*math.sin(q2)**2*math.sin(q1 - q2)**2 + 16*d4**2*math.sin(q1)**2*math.sin(q2)**2 + 12*d4**2*math.sin(q1)**2*math.sin(q1 - q2)**2 - 42*d4**2*math.sin(q1)**2 + 16*d4**2*math.sin(q1)*math.sin(q2)**2*math.sin(q1 - q2)*math.cos(q2) - 48*d4**2*math.sin(q1)*math.sin(q1 - q2)*math.cos(q2) + 16*d4**2*math.sin(q2)**2 + 12*d4**2*math.cos(q2)**2 - 42*d4**2 - 16*d4*math.sin(q1)*math.sin(q2)**2*math.sin(q1 - q2) + 24*d4*math.sin(q1)*math.sin(q1 - q2) - 24*d4*math.cos(q2) + 64*math.sin(q2)**2 - 156) + (-T2 + d4dot*(q1dot*(0.5*d4*math.sin(q1)*math.sin(q2)*math.cos(q1 - q2) + 0.5*(d4*math.cos(q2) + 2)*math.sin(q1)*math.sin(q1 - q2) + 1.0*math.cos(q2)) + q2dot*(1.0*d4 + 2.0*math.cos(q2))) + q1dot*(d4dot*(0.5*d4*math.sin(q1)*math.sin(q2)*math.cos(q1 - q2) + 0.5*(d4*math.cos(q2) + 2)*math.sin(q1)*math.sin(q1 - q2) + 1.0*math.cos(q2)) + q1dot*(-2.0*d4*math.sin(q1)*math.cos(q1 - q2) + 1.0*(d4*math.cos(q2) + 2)*(d4*math.sin(q1)*math.cos(q1 - q2) + d4*math.sin(q1 - q2)*math.cos(q1)))) + q2dot*(-2.0*d4*q2dot*math.sin(q2) + d4dot*(1.0*d4 + 2.0*math.cos(q2))))*(d4**2*math.sin(q1)**2*math.sin(q2)**2*math.sin(q1 - q2)**2 - 3*d4**2*math.sin(q1)**2 - 8*d4*math.sin(q1)*math.sin(q2)**2*math.sin(q1 - q2) + 12*d4*math.sin(q1)*math.sin(q1 - q2) + 16*math.sin(q2)**2 - 42)/(d4**4*math.sin(q1)**2*math.sin(q2)**2*math.sin(q1 - q2)**2 + 3*d4**4*math.sin(q1)**2*math.sin(q1 - q2)**2*math.cos(q2)**2 - 3*d4**4*math.sin(q1)**2 - 4*d4**3*math.sin(q1)**2*math.sin(q2)**2*math.sin(q1 - q2)**2*math.cos(q2) + 12*d4**3*math.sin(q1)**2*math.sin(q1 - q2)**2*math.cos(q2) - 12*d4**3*math.sin(q1)**2*math.cos(q2) - 8*d4**3*math.sin(q1)*math.sin(q2)**2*math.sin(q1 - q2) - 12*d4**3*math.sin(q1)*math.sin(q1 - q2)*math.cos(q2)**2 + 12*d4**3*math.sin(q1)*math.sin(q1 - q2) - 2*d4**2*math.sin(q1)**2*math.sin(q2)**2*math.sin(q1 - q2)**2 + 16*d4**2*math.sin(q1)**2*math.sin(q2)**2 + 12*d4**2*math.sin(q1)**2*math.sin(q1 - q2)**2 - 42*d4**2*math.sin(q1)**2 + 16*d4**2*math.sin(q1)*math.sin(q2)**2*math.sin(q1 - q2)*math.cos(q2) - 48*d4**2*math.sin(q1)*math.sin(q1 - q2)*math.cos(q2) + 16*d4**2*math.sin(q2)**2 + 12*d4**2*math.cos(q2)**2 - 42*d4**2 - 16*d4*math.sin(q1)*math.sin(q2)**2*math.sin(q1 - q2) + 24*d4*math.sin(q1)*math.sin(q1 - q2) - 24*d4*math.cos(q2) + 64*math.sin(q2)**2 - 156) + (-T1 + d4dot*(1.0*d4dot*math.sin(q1)*math.sin(q2)*math.sin(q1 - q2) + q1dot*(1.0*d4*math.sin(q1)**2 - 2.0*math.sin(q1)*math.sin(q1 - q2)) + q2dot*(-0.5*d4*math.sin(q1)*math.sin(q2)*math.cos(q1 - q2) + 0.5*(d4*math.cos(q2) + 2)*math.sin(q1)*math.sin(q1 - q2) + 1.0*(d4*math.sin(q1)*math.sin(q1 - q2) - 2)*math.cos(q2) - 1.0*math.cos(q2))) + q1dot*(2.0*d4*q2dot*math.sin(q1)*math.cos(q1 - q2) + d4dot*(1.0*d4*math.sin(q1)**2 - 2.0*math.sin(q1)*math.sin(q1 - q2)) + q1dot*(1.0*d4**2*math.sin(q1)*math.cos(q1) - 2.0*d4*math.sin(q1)*math.cos(q1 - q2) - 2.0*d4*math.sin(q1 - q2)*math.cos(q1))) + q2dot*(2.0*d4*q1dot*math.sin(q1)*math.cos(q1 - q2) + d4dot*(-0.5*d4*math.sin(q1)*math.sin(q2)*math.cos(q1 - q2) + 0.5*(d4*math.cos(q2) + 2)*math.sin(q1)*math.sin(q1 - q2) + 1.0*(d4*math.sin(q1)*math.sin(q1 - q2) - 2)*math.cos(q2) - 1.0*math.cos(q2)) + q2dot*(-1.0*d4*(d4*math.cos(q2) + 2)*math.sin(q1)*math.cos(q1 - q2) - 1.0*d4*(d4*math.sin(q1)*math.sin(q1 - q2) - 2)*math.sin(q2))) + ((1/2)*d4 + 3.0)*math.cos(q1) + 3.0*math.cos(q1))*(3*d4**2*math.sin(q1)*math.sin(q1 - q2)*math.cos(q2) - 4*d4*math.sin(q1)*math.sin(q2)**2*math.sin(q1 - q2) + 6*d4*math.sin(q1)*math.sin(q1 - q2) - 6*d4*math.cos(q2) + 16*math.sin(q2)**2 - 36)/(d4**4*math.sin(q1)**2*math.sin(q2)**2*math.sin(q1 - q2)**2 + 3*d4**4*math.sin(q1)**2*math.sin(q1 - q2)**2*math.cos(q2)**2 - 3*d4**4*math.sin(q1)**2 - 4*d4**3*math.sin(q1)**2*math.sin(q2)**2*math.sin(q1 - q2)**2*math.cos(q2) + 12*d4**3*math.sin(q1)**2*math.sin(q1 - q2)**2*math.cos(q2) - 12*d4**3*math.sin(q1)**2*math.cos(q2) - 8*d4**3*math.sin(q1)*math.sin(q2)**2*math.sin(q1 - q2) - 12*d4**3*math.sin(q1)*math.sin(q1 - q2)*math.cos(q2)**2 + 12*d4**3*math.sin(q1)*math.sin(q1 - q2) - 2*d4**2*math.sin(q1)**2*math.sin(q2)**2*math.sin(q1 - q2)**2 + 16*d4**2*math.sin(q1)**2*math.sin(q2)**2 + 12*d4**2*math.sin(q1)**2*math.sin(q1 - q2)**2 - 42*d4**2*math.sin(q1)**2 + 16*d4**2*math.sin(q1)*math.sin(q2)**2*math.sin(q1 - q2)*math.cos(q2) - 48*d4**2*math.sin(q1)*math.sin(q1 - q2)*math.cos(q2) + 16*d4**2*math.sin(q2)**2 + 12*d4**2*math.cos(q2)**2 - 42*d4**2 - 16*d4*math.sin(q1)*math.sin(q2)**2*math.sin(q1 - q2) + 24*d4*math.sin(q1)*math.sin(q1 - q2) - 24*d4*math.cos(q2) + 64*math.sin(q2)**2 - 156)
    dzddt= (-F + q1dot*(q1dot*(-1.0*d4*math.sin(q1)**2 + 1.0*(d4*math.sin(q1)*math.cos(q1 - q2) + d4*math.sin(q1 - q2)*math.cos(q1))*math.sin(q2) + 2.0*math.sin(q1)*math.sin(q1 - q2)) + q2dot*(-0.5*d4*math.sin(q1)*math.sin(q2)*math.cos(q1 - q2) - 0.5*(d4*math.cos(q2) + 2)*math.sin(q1)*math.sin(q1 - q2) - 1.0*math.cos(q2))) + q2dot*(q1dot*(-0.5*d4*math.sin(q1)*math.sin(q2)*math.cos(q1 - q2) - 0.5*(d4*math.cos(q2) + 2)*math.sin(q1)*math.sin(q1 - q2) - 1.0*math.cos(q2)) + q2dot*(-1.0*d4 + 2.0*math.cos(q2))) + (1/2)*math.sin(q1))*(d4**4*math.sin(q1)**2*math.sin(q1 - q2)**2*math.cos(q2)**2 - d4**4*math.sin(q1)**2 + 4*d4**3*math.sin(q1)**2*math.sin(q1 - q2)**2*math.cos(q2) - 4*d4**3*math.sin(q1)**2*math.cos(q2) - 4*d4**3*math.sin(q1)*math.sin(q1 - q2)*math.cos(q2)**2 + 4*d4**3*math.sin(q1)*math.sin(q1 - q2) + 4*d4**2*math.sin(q1)**2*math.sin(q1 - q2)**2 - 14*d4**2*math.sin(q1)**2 - 16*d4**2*math.sin(q1)*math.sin(q1 - q2)*math.cos(q2) + 4*d4**2*math.cos(q2)**2 - 14*d4**2 + 8*d4*math.sin(q1)*math.sin(q1 - q2) - 8*d4*math.cos(q2) - 52)/(d4**4*math.sin(q1)**2*math.sin(q2)**2*math.sin(q1 - q2)**2 + 3*d4**4*math.sin(q1)**2*math.sin(q1 - q2)**2*math.cos(q2)**2 - 3*d4**4*math.sin(q1)**2 - 4*d4**3*math.sin(q1)**2*math.sin(q2)**2*math.sin(q1 - q2)**2*math.cos(q2) + 12*d4**3*math.sin(q1)**2*math.sin(q1 - q2)**2*math.cos(q2) - 12*d4**3*math.sin(q1)**2*math.cos(q2) - 8*d4**3*math.sin(q1)*math.sin(q2)**2*math.sin(q1 - q2) - 12*d4**3*math.sin(q1)*math.sin(q1 - q2)*math.cos(q2)**2 + 12*d4**3*math.sin(q1)*math.sin(q1 - q2) - 2*d4**2*math.sin(q1)**2*math.sin(q2)**2*math.sin(q1 - q2)**2 + 16*d4**2*math.sin(q1)**2*math.sin(q2)**2 + 12*d4**2*math.sin(q1)**2*math.sin(q1 - q2)**2 - 42*d4**2*math.sin(q1)**2 + 16*d4**2*math.sin(q1)*math.sin(q2)**2*math.sin(q1 - q2)*math.cos(q2) - 48*d4**2*math.sin(q1)*math.sin(q1 - q2)*math.cos(q2) + 16*d4**2*math.sin(q2)**2 + 12*d4**2*math.cos(q2)**2 - 42*d4**2 - 16*d4*math.sin(q1)*math.sin(q2)**2*math.sin(q1 - q2) + 24*d4*math.sin(q1)*math.sin(q1 - q2) - 24*d4*math.cos(q2) + 64*math.sin(q2)**2 - 156) + (-T2 + d4dot*(q1dot*(0.5*d4*math.sin(q1)*math.sin(q2)*math.cos(q1 - q2) + 0.5*(d4*math.cos(q2) + 2)*math.sin(q1)*math.sin(q1 - q2) + 1.0*math.cos(q2)) + q2dot*(1.0*d4 + 2.0*math.cos(q2))) + q1dot*(d4dot*(0.5*d4*math.sin(q1)*math.sin(q2)*math.cos(q1 - q2) + 0.5*(d4*math.cos(q2) + 2)*math.sin(q1)*math.sin(q1 - q2) + 1.0*math.cos(q2)) + q1dot*(-2.0*d4*math.sin(q1)*math.cos(q1 - q2) + 1.0*(d4*math.cos(q2) + 2)*(d4*math.sin(q1)*math.cos(q1 - q2) + d4*math.sin(q1 - q2)*math.cos(q1)))) + q2dot*(-2.0*d4*q2dot*math.sin(q2) + d4dot*(1.0*d4 + 2.0*math.cos(q2))))*(-d4**3*math.sin(q1)**2*math.sin(q2)*math.sin(q1 - q2)**2*math.cos(q2) - 2*d4**2*math.sin(q1)**2*math.sin(q2)*math.sin(q1 - q2)**2 + 4*d4**2*math.sin(q1)**2*math.sin(q2) + 6*d4**2*math.sin(q1)*math.sin(q2)*math.sin(q1 - q2)*math.cos(q2) + 4*d4*math.sin(q1)*math.sin(q2)*math.sin(q1 - q2) - 8*d4*math.sin(q2)*math.cos(q2) + 8*math.sin(q2))/(d4**4*math.sin(q1)**2*math.sin(q2)**2*math.sin(q1 - q2)**2 + 3*d4**4*math.sin(q1)**2*math.sin(q1 - q2)**2*math.cos(q2)**2 - 3*d4**4*math.sin(q1)**2 - 4*d4**3*math.sin(q1)**2*math.sin(q2)**2*math.sin(q1 - q2)**2*math.cos(q2) + 12*d4**3*math.sin(q1)**2*math.sin(q1 - q2)**2*math.cos(q2) - 12*d4**3*math.sin(q1)**2*math.cos(q2) - 8*d4**3*math.sin(q1)*math.sin(q2)**2*math.sin(q1 - q2) - 12*d4**3*math.sin(q1)*math.sin(q1 - q2)*math.cos(q2)**2 + 12*d4**3*math.sin(q1)*math.sin(q1 - q2) - 2*d4**2*math.sin(q1)**2*math.sin(q2)**2*math.sin(q1 - q2)**2 + 16*d4**2*math.sin(q1)**2*math.sin(q2)**2 + 12*d4**2*math.sin(q1)**2*math.sin(q1 - q2)**2 - 42*d4**2*math.sin(q1)**2 + 16*d4**2*math.sin(q1)*math.sin(q2)**2*math.sin(q1 - q2)*math.cos(q2) - 48*d4**2*math.sin(q1)*math.sin(q1 - q2)*math.cos(q2) + 16*d4**2*math.sin(q2)**2 + 12*d4**2*math.cos(q2)**2 - 42*d4**2 - 16*d4*math.sin(q1)*math.sin(q2)**2*math.sin(q1 - q2) + 24*d4*math.sin(q1)*math.sin(q1 - q2) - 24*d4*math.cos(q2) + 64*math.sin(q2)**2 - 156) + (d4**3*math.sin(q1)*math.sin(q2)*math.sin(q1 - q2) - 4*d4**2*math.sin(q2) + 6*d4*math.sin(q1)*math.sin(q2)*math.sin(q1 - q2) - 8*d4*math.sin(q2)*math.cos(q2) - 8*math.sin(q2))*(-T1 + d4dot*(1.0*d4dot*math.sin(q1)*math.sin(q2)*math.sin(q1 - q2) + q1dot*(1.0*d4*math.sin(q1)**2 - 2.0*math.sin(q1)*math.sin(q1 - q2)) + q2dot*(-0.5*d4*math.sin(q1)*math.sin(q2)*math.cos(q1 - q2) + 0.5*(d4*math.cos(q2) + 2)*math.sin(q1)*math.sin(q1 - q2) + 1.0*(d4*math.sin(q1)*math.sin(q1 - q2) - 2)*math.cos(q2) - 1.0*math.cos(q2))) + q1dot*(2.0*d4*q2dot*math.sin(q1)*math.cos(q1 - q2) + d4dot*(1.0*d4*math.sin(q1)**2 - 2.0*math.sin(q1)*math.sin(q1 - q2)) + q1dot*(1.0*d4**2*math.sin(q1)*math.cos(q1) - 2.0*d4*math.sin(q1)*math.cos(q1 - q2) - 2.0*d4*math.sin(q1 - q2)*math.cos(q1))) + q2dot*(2.0*d4*q1dot*math.sin(q1)*math.cos(q1 - q2) + d4dot*(-0.5*d4*math.sin(q1)*math.sin(q2)*math.cos(q1 - q2) + 0.5*(d4*math.cos(q2) + 2)*math.sin(q1)*math.sin(q1 - q2) + 1.0*(d4*math.sin(q1)*math.sin(q1 - q2) - 2)*math.cos(q2) - 1.0*math.cos(q2)) + q2dot*(-1.0*d4*(d4*math.cos(q2) + 2)*math.sin(q1)*math.cos(q1 - q2) - 1.0*d4*(d4*math.sin(q1)*math.sin(q1 - q2) - 2)*math.sin(q2))) + ((1/2)*d4 + 3.0)*math.cos(q1) + 3.0*math.cos(q1))/(d4**4*math.sin(q1)**2*math.sin(q2)**2*math.sin(q1 - q2)**2 + 3*d4**4*math.sin(q1)**2*math.sin(q1 - q2)**2*math.cos(q2)**2 - 3*d4**4*math.sin(q1)**2 - 4*d4**3*math.sin(q1)**2*math.sin(q2)**2*math.sin(q1 - q2)**2*math.cos(q2) + 12*d4**3*math.sin(q1)**2*math.sin(q1 - q2)**2*math.cos(q2) - 12*d4**3*math.sin(q1)**2*math.cos(q2) - 8*d4**3*math.sin(q1)*math.sin(q2)**2*math.sin(q1 - q2) - 12*d4**3*math.sin(q1)*math.sin(q1 - q2)*math.cos(q2)**2 + 12*d4**3*math.sin(q1)*math.sin(q1 - q2) - 2*d4**2*math.sin(q1)**2*math.sin(q2)**2*math.sin(q1 - q2)**2 + 16*d4**2*math.sin(q1)**2*math.sin(q2)**2 + 12*d4**2*math.sin(q1)**2*math.sin(q1 - q2)**2 - 42*d4**2*math.sin(q1)**2 + 16*d4**2*math.sin(q1)*math.sin(q2)**2*math.sin(q1 - q2)*math.cos(q2) - 48*d4**2*math.sin(q1)*math.sin(q1 - q2)*math.cos(q2) + 16*d4**2*math.sin(q2)**2 + 12*d4**2*math.cos(q2)**2 - 42*d4**2 - 16*d4*math.sin(q1)*math.sin(q2)**2*math.sin(q1 - q2) + 24*d4*math.sin(q1)*math.sin(q1 - q2) - 24*d4*math.cos(q2) + 64*math.sin(q2)**2 - 156)
    dydt = [dq1dt,dq2dt,dzdt,dq1ddt,dq2ddt,dzddt]
    return dydt



initstate = [Q1[0],Q2[0],D4[0],0,0,0] # initial states
timestep = 0.1

time = np.linspace(0,7, 7) # define the time for which we want to solve


# solve the ODE. solve_ivp is the most recent version of the solver. Check docs for more information on how to use.
solution = solve_ivp(Model, [0, time[-1]], initstate, t_eval= time) 
Q1n=solution.y[0]
Q2n=solution.y[1]
D4n=solution.y[2]
Q1DOT=solution.y[3]
Q2DOT=solution.y[4]
D4DOT=solution.y[5]
Q1n


array([0.65874639, 1.49127251, 2.636459  , 2.60230571, 1.54156307,
       0.84043454, 1.45164257])