CODE VERIFIER FOR Q1 (C)  ABCD FOR STAND FORD

In [21]:
import numpy as np

x1=[0]*3;
x2=[0]*3;
x3=[0]*3;
x4=[0]*3;
k1=[0]*3;
k2=[0]*3;
k3=[0]*3;
k4=[0]*3;
      
for n in range(3):
    print("enter the endefector A x,y,z in sequemce");
    x1[n]=float(input());
for n in range(3):
    print("enter the endefector B x,y,z in sequemce");
    x2[n]=float(input());
for n in range(3):
    print("enter the endefector C x,y,z in sequemce");
    x3[n]=float(input());
for n in range(3):
    print("enter the endefector D x,y,z in sequemce");
    x4[n]=float(input());
print("enter the length of d1 ");
d1=int(input());#length of first joint
print("enter the length of d2 ");
d2=float(input());#length of first joint
if(x1[0]!=0):
    theta1=np.arctan(x1[1]/x1[0]);
else:
    theta1=np.pi/2;
    

d=np.sqrt(x1[1]**2+x1[0]**2);
#s=x1[2]-d1
s=-x1[2]+d1
theta2=np.arctan(s/d);
l=np.sqrt(s**2+d**2);
d3=l-d2;
k1=[(180/np.pi)*theta1,(180/np.pi)*theta2,d3]
print(k1);
#B
if(x2[0]!=0):
    theta1=np.arctan(x2[1]/x2[0]);
else:
    theta1=np.pi/2;
    

d=np.sqrt(x2[1]**2+x2[0]**2);
#s=x2[2]-d1
s=-x2[2]+d1
theta2=np.arctan(s/d);
l=np.sqrt(s**2+d**2);
d3=l-d2;
k2=[(180/np.pi)*theta1,(180/np.pi)*theta2,d3]
print(k2);

#C
if(x3[0]!=0):
  theta1=np.arctan(x3[1]/x3[0]);

    
else:
  theta1=np.pi/2;

    
    

d=np.sqrt(x3[1]**2+x3[0]**2);
#s=x3[2]-d1
s=-x3[2]+d1
theta2=np.arctan(s/d);
l=np.sqrt(s**2+d**2);
d3=l-d2;
k3=[(180/np.pi)*theta1,(180/np.pi)*theta2,d3]
print(k3);

#D
if(x4[0]!=0):
    theta1=np.arctan(x4[1]/x4[0]);
else:
    theta1=np.pi/2;
    

d=np.sqrt(x4[1]**2+x4[0]**2);
#s=x4[2]-d1
s=-x4[2]+d1
theta2=np.arctan(s/d);
l=np.sqrt(s**2+d**2);
d3=l-d2;
k4=[(180/np.pi)*theta1,(180/np.pi)*theta2,d3]
print(k4);





enter the endefector A x,y,z in sequemce
40
enter the endefector A x,y,z in sequemce
6
enter the endefector A x,y,z in sequemce
10
enter the endefector B x,y,z in sequemce
40
enter the endefector B x,y,z in sequemce
1
enter the endefector B x,y,z in sequemce
10
enter the endefector C x,y,z in sequemce
35
enter the endefector C x,y,z in sequemce
1
enter the endefector C x,y,z in sequemce
10
enter the endefector D x,y,z in sequemce
35
enter the endefector D x,y,z in sequemce
6
enter the endefector D x,y,z in sequemce
10
enter the length of d1 
25
enter the length of d2 
25
[8.530765609948133, 20.347355912916147, 18.139309220245984]
[1.4320961841646465, 20.55016119820984, 17.731721238442994]
[1.6365770416167182, 23.190127802039573, 13.091993909481822]
[9.727578551401603, 22.899659632930643, 13.548670534792763]


CODE VERIFIER FOR RANDOM ABCD SCARA

In [22]:
import numpy as np

x1=[0]*3;
x2=[0]*3;
x3=[0]*3;
x4=[0]*3;
k1=[0]*3;
k2=[0]*3;
k3=[0]*3;
k4=[0]*3;
      

for n in range(3):
    print("enter the endefector A x,y,z in sequemce");
    x1[n]=float(input());
for n in range(3):
    print("enter the endefector B x,y,z in sequemce");
    x2[n]=float(input());
for n in range(3):
    print("enter the endefector C x,y,z in sequemce");
    x3[n]=float(input());
for n in range(3):
    print("enter the endefector D x,y,z in sequemce");
    x4[n]=float(input());
print("enter the length of offset ");
offset=int(input());#length of offset of first joint from ground
print("enter the length of d1 ");
d1=int(input());#length of first joint
print("enter the length of d2 ");
d2=float(input());#length of first joint
#A
r = abs((x1[0]**2+x1[1]**2-d1**2-d2**2)/(2*d1*d2))
theta2 = np.arctan(np.sqrt(abs(1-r**2))/r)
theta1 = np.arctan(x1[1]/x1[0]) - np.arctan((d2*np.sin(theta2))/(d1+d2*np.cos(theta2)))
d3 =offset-x1[2]

k1=[(180/np.pi)*theta1,(180/np.pi)*theta2,d3]
print(k1);
#B
r = abs((x2[0]**2+x2[1]**2-d1**2-d2**2)/(2*d1*d2))
theta2 = np.arctan(np.sqrt(abs(1-r**2))/r)
theta1 = np.arctan(x2[1]/x2[0]) - np.arctan((d2*np.sin(theta2))/(d1+d2*np.cos(theta2)))
d3 =offset-x2[2]

k2=[(180/np.pi)*theta1,(180/np.pi)*theta2,d3]
print(k2);

#C
r = abs((x3[0]**2+x3[1]**2-d1**2-d2**2)/(2*d1*d2))
theta2 = np.arctan(np.sqrt(abs(1-r**2))/r)
theta1 = np.arctan(x3[1]/x3[0]) - np.arctan((d2*np.sin(theta2))/(d1+d2*np.cos(theta2)))
d3 =offset-x3[2]

k3=[(180/np.pi)*theta1,(180/np.pi)*theta2,d3]
print(k3);

#D
r = abs((x4[0]**2+x4[1]**2-d1**2-d2**2)/(2*d1*d2))
theta2 = np.arctan(np.sqrt(abs(1-r**2))/r)
theta1 = np.arctan(x4[1]/x4[0]) - np.arctan((d2*np.sin(theta2))/(d1+d2*np.cos(theta2)))
d3 =offset-x4[2]

k4=[(180/np.pi)*theta1,(180/np.pi)*theta2,d3]
print(k4);



enter the endefector A x,y,z in sequemce
40
enter the endefector A x,y,z in sequemce
6
enter the endefector A x,y,z in sequemce
10
enter the endefector B x,y,z in sequemce
40
enter the endefector B x,y,z in sequemce
1
enter the endefector B x,y,z in sequemce
10
enter the endefector C x,y,z in sequemce
35
enter the endefector C x,y,z in sequemce
1
enter the endefector C x,y,z in sequemce
10
enter the endefector D x,y,z in sequemce
35
enter the endefector D x,y,z in sequemce
6
enter the endefector D x,y,z in sequemce
10
enter the length of offset 
25
enter the length of d1 
25
enter the length of d2 
25
[-27.475770490137336, 72.01307220017094, 15.0]
[-35.41392531548361, 73.6920429992965, 15.0]
[-42.81334967502451, 88.89985343328247, 15.0]
[-35.02031676483832, 89.49579063247985, 15.0]


inverse calculator for ABCD PUMA

In [23]:
import numpy as np

x1=[0]*3;
x2=[0]*3;
x3=[0]*3;
x4=[0]*3;
k1=[0]*3;
k2=[0]*3;
k3=[0]*3;
k4=[0]*3;
      

for n in range(3):
    print("enter the endefector A x,y,z in sequemce");
    x1[n]=float(input());
for n in range(3):
    print("enter the endefector B x,y,z in sequemce");
    x2[n]=float(input());
for n in range(3):
    print("enter the endefector C x,y,z in sequemce");
    x3[n]=float(input());
for n in range(3):
    print("enter the endefector D x,y,z in sequemce");
    x4[n]=float(input());
print("enter the length of d1 ");
d1=int(input());#length of offset of first joint from ground
print("enter the length of d2 ");
d2=int(input());#length of first joint
print("enter the length of d3 ");
d3=float(input());#length of first joint

#A
n=x1[2]-d1;
m=np.sqrt(x1[0]**2+x1[1]**2);
theta1=np.arctan(x1[1]/x1[0]);
r = (m**2+n**2-d2**2-d3**2)/(2*d2*d3)
theta3 = np.arctan(np.sqrt(1-r**2)/r)
theta2 = np.arctan(n/m) - np.arctan((d3*np.sin(theta3))/(d2+d3*np.cos(theta3)))
k1=[(180/np.pi)*theta1,(180/np.pi)*theta2,(180/np.pi)*theta3]
print(k1);

#B
n=x2[2]-d1;
m=np.sqrt(x2[0]**2+x2[1]**2);
theta1=np.arctan(x2[1]/x2[0]);
r = (m**2+n**2-d2**2-d3**2)/(2*d2*d3)
theta3 = np.arctan(np.sqrt(1-r**2)/r)
theta2 = np.arctan(n/m) - np.arctan((d3*np.sin(theta3))/(d2+d3*np.cos(theta3)))
k2=[(180/np.pi)*theta1,(180/np.pi)*theta2,(180/np.pi)*theta3]
print(k2);

#C
n=x3[2]-d1;
m=np.sqrt(x3[0]**2+x3[1]**2);
theta1=np.arctan(x3[1]/x3[0]);
r = (m**2+n**2-d2**2-d3**2)/(2*d2*d3)
theta3 = np.arctan(np.sqrt(1-r**2)/r)
theta2 = np.arctan(n/m) - np.arctan((d3*np.sin(theta3))/(d2+d3*np.cos(theta3)))
k3=[(180/np.pi)*theta1,(180/np.pi)*theta2,(180/np.pi)*theta3]
print(k3);

#D
n=x4[2]-d1;
m=np.sqrt(x4[0]**2+x4[1]**2);
theta1=np.arctan(x4[1]/x4[0]);
r = (m**2+n**2-d2**2-d3**2)/(2*d2*d3)
theta3 = np.arctan(np.sqrt(1-r**2)/r)
theta2 = np.arctan(n/m) - np.arctan((d3*np.sin(theta3))/(d2+d3*np.cos(theta3)))
k4=[(180/np.pi)*theta1,(180/np.pi)*theta2,(180/np.pi)*theta3]
print(k4);


enter the endefector A x,y,z in sequemce
40
enter the endefector A x,y,z in sequemce
6
enter the endefector A x,y,z in sequemce
10
enter the endefector B x,y,z in sequemce
40
enter the endefector B x,y,z in sequemce
1
enter the endefector B x,y,z in sequemce
10
enter the endefector C x,y,z in sequemce
35
enter the endefector C x,y,z in sequemce
1
enter the endefector C x,y,z in sequemce
10
enter the endefector D x,y,z in sequemce
35
enter the endefector D x,y,z in sequemce
6
enter the endefector D x,y,z in sequemce
10
enter the length of d1 
25
enter the length of d2 
25
enter the length of d3 
25
[8.530765609948133, -50.71648614651108, 60.73826046718986]
[1.4320961841646465, -51.83079015007423, 62.56125790372877]
[1.6365770416167182, -63.56346074215648, 80.7466658802338]
[9.727578551401603, -62.458278705245135, 79.11723814462898]


ALL THE ABOVE CALCULATED VALUES CAN BE CROSS CHECKEDD WITH BELOW CODE

In [24]:
import numpy as np
import scipy


#NOW WE MOVE TOWARDS CALCULATING THE DH TABLE

          
def my_function(j):

 A[0][0]=np.cos(theta[j]);
 A[0][1]=-np.sin(theta[j])*np.cos(alpha[j]);
 A[0][2]=np.sin(theta[j])*np.sin(alpha[j]);
 A[0][3]=np.cos(theta[j])*r[j];
 A[1][0]=np.sin(theta[j]);
 A[1][1]=np.cos(theta[j])*np.cos(alpha[j]);
 A[1][2]=-np.cos(theta[j])*np.sin(alpha[j]);
 A[1][3]=np.sin(theta[j])*r[j];
 A[2][0]=0;
 A[2][1]=np.sin(alpha[j]);
 A[2][2]=np.cos(alpha[j]);
 A[2][3]=depth[j];
 A[3][0]=0;
 A[3][1]=0;
 A[3][2]=0;
 A[3][3]=1;
 return A

#TRANSFORMATION MATRIX CALCULATOR
def my_funch(c,v):
    
     
    for i in range(c,v):
        if i!=c:
            B=B@np.array(my_function(i))
          
        else:
            B=np.array(my_function(i));
            

        
    return B;
 

#NOW WE MOVE TOWARDS JACOBIAN
def JacobianCol(i,l):
    
        z=[[0],[0],[0]];
        if joint[i]==0:#implies its prizmatic so we have to calculate only Z and later append it to zero
            Zo=ZIM1(i);
            K=np.transpose(z);
            K1=np.transpose(Zo);
            RAF=np.concatenate((K1,K),axis=1);
            RAF1=np.transpose(RAF);
            return(RAF1)
        else:#implies its revolute so we have to calculate only Z and later append it to zero
            omain=Ocal(l);
            ocha=Ocal(i);
            Ofin=omain-ocha;
            zag=ZIM1(i);
            zag2=np.transpose(zag);
            Ofim=np.transpose(Ofin);
                                                           
            PAF=np.cross(zag2,Ofim);
            PAF2=np.transpose(PAF);
            
            PAF1=np.concatenate((PAF2,zag),axis=0);
            return(PAF1);
            
        
            
 



#Z(I-1) CALCULATOR
def ZIM1(k):
 zat=[[0],[0],[1]];
 
 if k==0:
     return zat;
 else:
     RA=my_funch(0,k);
     RAn1=np.delete(RA,[3],0);
     RAn2=np.delete(RAn1,[3],1);
     
     zat=[[0],[0],[1]];
     KA=np.matmul(RAn2,zat);
     return KA
     
           
   
#On calcuator
def Ocal(k):
    rat=[[0],[0],[0]];
    if k==0:
        return rat;
    else:
        RA=my_funch(0,k);
        RAn1=np.delete(RA,[3],0);
        RAn2=np.delete(RAn1,[0,1,2],1);
        
        #KA=np.matmul(RAn2,np.transpose(ma));
        
        return RAn2;

        
        
print("enter the no. of links");
l=int(input());
joint= np.array([1]*l);
depth=[0]*l;
r=[0]*l;
theta=[0]*l;
alpha=[0]*l;

A = [[0 for x in range(4)] for y in range(4)] 



print("self mode or auto press 1 for auto 0 for self");
s=int(input());
if s==0:
    for i in range(l):
        print("please  enter 1 for revolute and 0 for prismatic");
        joint[i]=int(input());
else:
    joint=[1]*l;
    
for n in range(l):
    print("enter the depth for",n+1," link");
    depth[n]=float(input());
    print("enter the aaa for",n+1," link");
    r[n]=float(input()); #r=a
    print("enter the theta for",n+1," link in degrees");
    theta[n]=(np.pi/180)*float(input());
    print("enter the alpha for",n+1,"link in degrees");
    alpha[n]=(np.pi/180)*float(input());        
    
            
     


#FINAL CONCANATE FUNCTION OF JACOBIAN
for i in range(l):
    if i==0:
        J1=JacobianCol(i,l);
    else:
        J1=np.concatenate((J1,JacobianCol(i,l)),axis=1);

print("1JACOBIAN")
print(np.round_(J1,decimals=2))


#FINAL END EFFECTOR VELOCITY CALCULATION
vel=[0]*l;
for n in range(l):
    print("enter the endeff velocity vector for x y z as follows wrt last link");
    vel[n]=float(input());
#print(pos)
       

P2=np.matmul(J1,np.transpose(vel));
print("END EFFECTOR VELOCITY VECTOR")
print(np.round_(P2,decimals=2))
 
 


# CALCULATE THE END EFFECTOR POSITION VECTOR   
       
H=np.round_(my_funch(0,l))
P=np.delete(H,[3],0);
P3=np.delete(P,[0,1,2],1);
print("END EFFECTOR POSITION VECTOR")
print(np.round_(abs(P3),decimals=2))
print(H)

# CALCULATE THE FINAL R MATRIX
N=np.round_(my_funch(0,l))
RAn4=np.delete(N,[3],0);
RAn5=np.delete(RAn4,[3],1);
print("Final R");
print(np.round_(RAn5,decimals=2));

enter the no. of links
3
self mode or auto press 1 for auto 0 for self
1
enter the depth for 1  link
25
enter the aaa for 1  link
0
enter the theta for 1  link in degrees
8.53
enter the alpha for 1 link in degrees
90
enter the depth for 2  link
0
enter the aaa for 2  link
25
enter the theta for 2  link in degrees
-50.71
enter the alpha for 2 link in degrees
0
enter the depth for 3  link
0
enter the aaa for 3  link
25
enter the theta for 3  link in degrees
60.73
enter the alpha for 3 link in degrees
0
1JACOBIAN
[[-6.   14.83 -4.3 ]
 [40.    2.22 -0.65]
 [ 0.   40.45 24.62]
 [ 0.    0.15  0.15]
 [ 0.   -0.99 -0.99]
 [ 1.    0.    0.  ]]
enter the endeff velocity vector for x y z as follows wrt last link
0
enter the endeff velocity vector for x y z as follows wrt last link
0
enter the endeff velocity vector for x y z as follows wrt last link
0
END EFFECTOR VELOCITY VECTOR
[0. 0. 0. 0. 0. 0.]
END EFFECTOR POSITION VECTOR
[[40.]
 [ 6.]
 [10.]]
[[ 1. -0.  0. 40.]
 [ 0. -0. -1.  6.]
 [ 0.  1.