

**REPOSITORY FOR INTRODUCTION TO ROBOTICS**

**2R Manipulator - Fixed Axis**

Codes by Rohan, Aarish, Jaydeep K, Vaishnavi, Suraj



In [ ]:
import numpy as np

In [ ]:
# Forward Kinematics 2R Planar Fixed Axis
def forward_kinematics(q1, q2, l1, l2):
    x1 = l1 * np.cos(q1)
    y1 = l1 * np.sin(q1)
    x2 = l1 * np.cos(q1) + l2 * np.cos(q2)  # l2*np.cos(q2+q1) will be second term if q2 measured from link1
    y2 = l1 * np.sin(q1) + l2 * np.sin(q2)  # l2*np.sin(q2+q1) will be second term if q2 measured from link1
    return x1, y1, x2, y2

# Inverse Kinematics 2R Planar Fixed Axis
def inverse_kinematics(x, y, l1, l2, elbow):  # elbow parameter = 1 or -1 for elbow down and up configurations
    D = (x ** 2 + y ** 2 - l1 ** 2 - l2 ** 2) / (2 * l1 * l2)
    if elbow == 1:
        D = (x ** 2 + y ** 2 - l1 ** 2 - l2 ** 2) / (2 * l1 * l2)
        q2 = elbow * np.arctan2(np.sqrt(1 - D ** 2), D)  # q2 as measured from frame of link 1
        q1 = np.arctan2(y, x) - np.arctan2(l2 * np.sin(q2), l1 + l2 * np.cos(q2))
        q2 = q2 + q1  # if q2 is not measured from inertial frame then remove this line
    if elbow == -1:
        q2 = elbow * np.arctan2(np.sqrt(1 - D ** 2), D)  # q2 as measured from frame of link 1
        q1 = np.arctan2(y, x) - np.arctan2(l2 * np.sin(q2), l1 + l2 * np.cos(q2))
        q2 = q2 + q1  # if q2 is not measured from inertial frame then remove this line
    return q1, q2


**SCARA**

In [ ]:
  def scara_invkin(x,y,z,d1,d2):
    # using formulae from the textbook
    r = abs((self.x**2+self.y**2-self.d1**2-self.d2**2)/(2*self.d1*self.d2))
    theta2 = np.arctan(np.sqrt(abs(1-r**2))/r)
    theta1 = np.arctan(self.y/self.x) - np.arctan((self.d2*np.sin(theta2))/(self.d1+self.d2*np.cos(theta2)))
    d3 = -self.z
    # converting from radians to degrees
    theta1 = theta1*180/np.pi
    theta2 = theta2*180/np.pi

**Stanford**

In [ ]:
 
def inverse_kinematics(endeffector_position,lengthsoflinks):
    theta1 = np.arctan(endeffector_position[1]/endeffector_position[0])
    r = np.sqrt(endeffector_position[0]**2 + endeffector_position[1]**2)
    s = endeffector_position[2] - lengthsoflinks[0]
    theta2 = np.arctan(s/r)
    d3 = np.sqrt(r**2 + s**2) - lengthsoflinks[1]
    print("First Solution: \n", "Theta1 = ", theta1, "\n Theta2 =", theta2,"\n Extension: ", d3, "\n")
    print("Second Solution: \n", "Theta1 = ", np.pi + theta1, "\n Theta2 =", np.pi - theta2,"\n Extension:", d3)

inverse_kinematics([30,30,30],[10,10])

First Solution: 
 Theta1 =  0.7853981633974483 
 Theta2 = 0.4405106630046985 
 Extension:  36.9041575982343 

Second Solution: 
 Theta1 =  3.9269908169872414 
 Theta2 = 2.7010819905850947 
 Extension: 36.9041575982343


**Articulated**

In [ ]:
def inverse_kinematics(l1,l2,l3,xc,yc,zc):
    theta1 = np.rad2deg(math.atan2(yc,xc))
    D = (xc*xc+yc*yc+(zc-l1)*(zc-l1)-l2*l2-l3*l3)/(2*l2*l3)
    if D>=1 or D<=-1:
        print("singular configuration")
    if D>1 or D<-1:
        print("outside workspace")
    theta3 = (math.atan2((-math.sqrt(1-D*D)),D))
    theta2 = np.rad2deg(math.atan2(zc-l1,(math.sqrt(xc*xc+yc*yc)))-math.atan2((l3*math.sin(theta3)),(l2+l3*math.cos(theta3))))
    theta3 = np.rad2deg(theta3)
    return theta1,theta2,theta3

**Spherical Wrist**

In [ ]:
  def inverse_kinematics(rotation_matrix):
    rotation_matrix = np.reshape(rotation_matrix, (3,3))
    theta1 = np.arctan2(np.sqrt(abs(1 - rotation_matrix[2,2]**2)), rotation_matrix[2,2])
    theta2 = np.arctan2(-np.sqrt(abs(1 - rotation_matrix[2,2]**2)), rotation_matrix[2,2])
    phi1 = np.arctan2(rotation_matrix[1,2], rotation_matrix[0,2])
    phi2 = np.arctan2(-rotation_matrix[1,2], -rotation_matrix[0,2])
    psi1 = np.arctan2(-rotation_matrix[2,0], rotation_matrix[2,1])
    psi2 = np.arctan2(rotation_matrix[2,0], -rotation_matrix[2,1])
    print("First Solution: \n", "theta = ", theta1, "\n phi = ", phi1, "\n psi = ", psi1)
    print("Second Solution: \n", "theta = ", theta2, "\n phi = ", phi2, "\n psi = ", psi2)

**Homogenous Matrices Forward Kinematics from DH**

In [ ]:
# Link Parameters:    [a, alpha, d, theta]
# For Multiple Links: [[a, alpha, d, theta]
#                      [a, alpha, d, theta]
#                      [a, alpha, d, theta]]

def atransformation(LinkParameters):
    a = LinkParameters[0]
    d = LinkParameters[2]
    alpha = LinkParameters[1]
    theta = LinkParameters[3]
    A = np.array([[[np.cos(theta), -np.sin(theta) * np.cos(alpha), np.sin(theta) * np.sin(alpha), a * np.cos(theta)],
                   [np.sin(theta), np.cos(theta) * np.cos(alpha), -np.cos(theta) * np.sin(alpha), a * np.sin(theta)],
                   [0, np.sin(alpha), np.cos(alpha), d],
                   [0, 0, 0, 1]]])
    return (A)
a = 1
d = 0
alpha = 0
theta = np.pi/4
LinkParameters = [a, alpha, d, theta]
# Example
A = atransformation(LinkParameters)
print(A)

def forward_kinematics_homogenous_matrix(DH):
    A = np.identity(4)
    n = np.shape(DH)[0]

    for i in range(n):
        Anext = atransformation(DH[i])
        A = np.matmul(A,Anext)

    return A
# Example
LinkParameters = [[1, 0, 0, np.pi/2],[1, 0, 0, np.pi/4]]
T = forward_kinematics(LinkParameters)
print(T)

[[[ 0.70710678 -0.70710678  0.          0.70710678]
  [ 0.70710678  0.70710678 -0.          0.70710678]
  [ 0.          0.          1.          0.        ]
  [ 0.          0.          0.          1.        ]]]
[[[-0.70710678 -0.70710678  0.         -0.70710678]
  [ 0.70710678 -0.70710678  0.          1.70710678]
  [ 0.          0.          1.          0.        ]
  [ 0.          0.          0.          1.        ]]]


**Jacobian from DH 1**

In [ ]:
import numpy as np
import sys
import sympy as sym

class manipulator():

  def __init__(self, no_of_links, type_of_joints, dh_params):
    super().__init__()
    self.no_of_links = no_of_links
    self.type_of_joints = list(type_of_joints)
    self.dh_params = dh_params
    if len(self.dh_params) != self.no_of_links:
      print("ERROR: Please make sure the number of rows in the DH parameters provided is equal to the number of links.")
      sys.exit()
    self.dh_matrices = []
    for i in range(0, self.no_of_links):    
      temp = self.dh_params[i]
      theta = temp[0]
      d = temp[1]
      a = temp[2]
      alpha = temp[3]
      A1 = np.array([[np.cos(theta), -np.sin(theta), 0, 0],[np.sin(theta), np.cos(theta), 0, 0],[0, 0, 1, 0],[0, 0, 0, 1]])
      A2 = np.array([[1, 0, 0, 0],[0, 1, 0, 0],[0, 0, 1, d],[0, 0, 0, 1]])
      A3 = np.array([[1, 0, 0, a],[0, 1, 0, 0],[0, 0, 1, 0],[0, 0, 0, 1]])
      A4 = np.array([[1, 0, 0, 0],[0, np.cos(alpha), -np.sin(alpha), 0],[0, np.sin(alpha), np.cos(alpha), 0],[0, 0, 0, 1]])
      A_final = A1@A2@A3@A4
      self.dh_matrices.append(A_final)
    self.dh_matrices = np.array(self.dh_matrices)

    self.transform_matrices = []
    self.rotation_matrices = []

    for i in range(1, self.no_of_links+1):
      temp = self.dh_matrices[0]
      for j in range(1, i):
        temp = temp@self.dh_matrices[j]
      rot_temp = temp
      rot_temp = np.delete(rot_temp, (3), axis = 0)
      rot_temp = np.delete(rot_temp, (3), axis = 1)
      self.transform_matrices.append(temp)
      self.rotation_matrices.append(rot_temp)

    self.transform_matrices = np.array(self.transform_matrices)
    self.rotation_matrices = np.array(self.rotation_matrices)

    self.end_effector_posn = np.delete(self.transform_matrices[len(self.transform_matrices)-1]@np.array([[0],[0],[0],[1]]), (3), axis = 0)

    self.z = []
    self.origins = []
    self.z.append(np.array([[0],[0],[1]]))
    self.origins.append(np.array([[0],[0],[0]]))

    for i in range(0, self.no_of_links):
      temp_z = self.rotation_matrices[i]@np.array([[0],[0],[1]])
      self.z.append(temp_z)
      temp_origin = self.transform_matrices[i]@np.array([[0],[0],[0],[1]])
      temp_origin = np.delete(temp_origin, (3), axis = 0)
      self.origins.append(temp_origin)
    
    self.z = np.array(self.z)
    self.origins = np.array(self.origins)  
    self.jacobian = []
    for i in range(0,self.no_of_links):
      if self.type_of_joints[i] == "R":
        temp_1 = np.cross(self.z[i], self.end_effector_posn-self.origins[i], axis = 0)
        temp_2 = self.z[i]
      if self.type_of_joints[i] == "P":
        temp_1 = self.z[i]
        temp_2 = np.array([[0],[0],[0]])
      temp_jacobian = np.vstack((temp_1, temp_2))
      self.jacobian.append(temp_jacobian)
    self.jacobian = np.array(self.jacobian)
    self.jacobian = self.jacobian.reshape((self.no_of_links,6))
    self.jacobian = np.transpose(self.jacobian)
    self.Jv = np.delete(self.jacobian,(3,4,5), axis = 0)

    print("End Effector Position:")
    print(self.end_effector_posn)
    print("Manipulator Jacobian:")
    print(self.jacobian)
    print("Velocity Jacobian (can be multiplied with qdot to obtain end-effector velocity):")
    print(self.Jv)

my_robot = manipulator(3, "RRR", [[np.pi/3,0,1,0],[0,0,0,np.pi/2],[0,0,0,np.pi/2]])
print("STANFORD MANIPULATOR:")
stanford_manipulator = manipulator(3, "RRP", [[0,0,0,-np.pi/2],[0,2,0,np.pi/2],[0,2,0,0]])
print("SCARA MANIPULATOR:")
SCARA = manipulator(3, "RRP", [[0,0,2,0],[0,0,2,np.pi],[0,2,0,0]])
print("PPP MANIPULATOR:")
PPP = manipulator(3, "PPP", [[0,1,0,-np.pi/2],[-np.pi/2,2,0,-np.pi/2],[0,3,0,0]])
print("6R MANIPULATOR:")
R6 = manipulator(6, "RRRRRR", [[np.pi/2,1,0,-np.pi/2],[0,0,1,0],[0,0,1,np.pi/2],[0,0,0,np.pi/2],[0,0,0,-np.pi/2],[0,1,0,0]])

**Jacobian from DH 2**



In [ ]:
# Importing Libraries
import numpy as np
import matplotlib.pyplot as plt

# Creating Class Robot and defining functions
class Robot():
  def __init__(self, numberoflinks, DH_matrix,joint_types=-1):
    self.numberoflinks = numberoflinks
    self.DH_matrix = DH_matrix
    if(joint_types == -1):
      self.joint_types = [1]*numberoflinks
    else:
      self.joint_types = joint_types

  def transform_matrix(self):
    self.A = []
    self.R = []
    for i in range(self.numberoflinks):
      self.A.append(np.array([[np.cos(self.DH_matrix[i][0]), -np.sin(self.DH_matrix[i][0]) * np.cos(self.DH_matrix[i][3]), np.sin(self.DH_matrix[i][0]) * np.sin(self.DH_matrix[i][3]), self.DH_matrix[i][2] * np.cos(self.DH_matrix[i][0])],[np.sin(self.DH_matrix[i][0]), np.cos(self.DH_matrix[i][0]) * np.cos(self.DH_matrix[i][3]), -np.cos(self.DH_matrix[i][0]) * np.sin(self.DH_matrix[i][3]), self.DH_matrix[i][2] * np.sin(self.DH_matrix[i][0])],[0, np.sin(self.DH_matrix[i][3]), np.cos(self.DH_matrix[i][3]), self.DH_matrix[i][1]],[0, 0, 0, 1]])) 
      self.R.append(np.array([[np.cos(self.DH_matrix[i][0]), -np.sin(self.DH_matrix[i][0]) * np.cos(self.DH_matrix[i][3]), np.sin(self.DH_matrix[i][0]) * np.sin(self.DH_matrix[i][3])],[np.sin(self.DH_matrix[i][0]), np.cos(self.DH_matrix[i][0]) * np.cos(self.DH_matrix[i][3]), -np.cos(self.DH_matrix[i][0]) * np.sin(self.DH_matrix[i][3])],[0, np.sin(self.DH_matrix[i][3]), np.cos(self.DH_matrix[i][3])]]))
    self.A = np.array(self.A) # Array of Homogenous Transformation Matrices
    self.R = np.array(self.R) # Array of Rotation matrices
    
    # Creating array of R_0_n matrices (R01, R02, R03, R04 ...)
    self.R_0_n = []
    A = np.identity(3)
    for i in range(self.numberoflinks):
      self.R_0_n.append(A)
      A = np.matmul(A, self.R[i])
    self.R_0_n.append(A)
    self.R_0_n = np.array(self.R_0_n)

    # Creating array of H_0_n matrices (H01, H02, H03, H04 ...)
    self.H_0_n = []
    B = np.identity(4)
    for i in range(self.numberoflinks):
      self.H_0_n.append(B)
      B = np.matmul(B, self.A[i])
    self.H_0_n.append(B)
    self.H_0_n = np.array(self.H_0_n)
    
    # Calculating Final Transfornation Matrix
    T = np.asmatrix(np.identity(4))
    for j in range(self.numberoflinks):
        T = T * np.asmatrix(self.A[j]) #,dtype = 'int' for integer output
    self.T = T
    # print ("A Matrices are: \n", self.A)
    # print ("Final Transformation Matrix: \n",T)
    # print ("Rotation Matrices are: \n", self.R)
    # print ("Rotation Matrices w.r.t base frame are: \n", self.R_0_n)
  
  def manipulator_jacobian(self):
    # Creating z terms
    self.z = []
    k = np.array([[0],[0],[1]])
    for i in range(self.numberoflinks+1):
      self.z.append(np.matmul(self.R_0_n[i],k))
    self.z = np.array(self.z)

    # Creating O terms
    d = np.array([[0],[0],[0],[1]])
    self.O = np.matmul(self.H_0_n,d)[:self.numberoflinks+1]
    self.On = np.delete(self.O,(3),axis=1)

    # Creating Jacobian Manipulator (Here J1 will be 0th element of array J and so on)
    self.J = []
    for i in range(self.numberoflinks):
      if self.joint_types[i] == 1:
        X = self.On[-1] - self.On[i]
        J_v = np.cross(self.z[i], X,axis = 0)
        J_v = np.vstack((J_v, self.z[i]))
        self.J.append(J_v)
      else:
        J_v = np.vstack((self.z[i], np.array([[0],[0],[0]])))
        self.J.append(J_v)
    self.J = np.array(self.J)
    self.J_v = np.delete(self.J, (3,4,5), axis = 1)
    print ("Manipulator Jacobian: \n", self.J)
    # print ("End effector position: \n", self.On[-1])
    # print ("End effector velocity: \n", "v = ", self.J_v, " x q_dot")

  def joint_velocities(self, xdot, ydot, zdot):
    X_dot  =np.array([[xdot],[ydot],[zdot]])
    J_v = self.J_v.reshape((3,3))
    Jacobian_Rank = np.linalg.matrix_rank(J_v)
    Augmentedmatrix_Rank = np.linalg.matrix_rank(np.hstack((J_v, X_dot)))
    if Jacobian_Rank != Augmentedmatrix_Rank:
      print("ERROR: Velocities provided are not possible for the given configuration")
      sys.exit()
    else:
      q_dot = np.linalg.pinv(J_v) @ X_dot
      print("Joint Velocities are given by: \n", q_dot)

# Initializing object "robot" and calculating result
# Mention the number of links in the first input
# Enter the DH table row wise in the order: [THETA, D, A, ALPHA]
# Enter Rho values for each link: 1 for Revolute and 0 for Prismatic
robot = Robot(2,[[0, 0, 1, 0],[0, 0, 1, 0]],joint_types = [0,0])
robot.transform_matrix()
robot.manipulator_jacobian()



Manipulator Jacobian: 
 [[[0.]
  [0.]
  [1.]
  [0.]
  [0.]
  [0.]]

 [[0.]
  [0.]
  [1.]
  [0.]
  [0.]
  [0.]]]


**Dynamics from D and V matrix**

In [ ]:
import numpy as np
import sympy as sp
import matplotlib.pyplot as plt

# Creating Class Robot and defining functions
class Robot():
  def __init__(self, numberoflinks, D_q, V_q):
    self.numberoflinks = numberoflinks
    self.D_q = D_q
    self.V_q = V_q

  def derive_equations(self):
    Phi = [0] * self.numberoflinks # Creating phi matrix
    c = [[[0] * self.numberoflinks] * self.numberoflinks] * self.numberoflinks # Creating c matrix
    T = [0] * self.numberoflinks # Matrix to store torque values for each link
    d = 0
    ct = 0

    # Calculating Christoffer Symbols
    for k in range(self.numberoflinks):
      for j in range(self.numberoflinks):
        for i in range(self.numberoflinks):
          c[i][j][k] = 0.5 * (sp.diff(self.D_q[k][j], q[i]) + sp.diff(self.D_q[k][i], q[j]) - sp.diff(self.D_q[i][j], q[k]))
    
    for k in range(self.numberoflinks): #corresponds to each link
      Phi[k] = sp.diff(self.V_q, q[k])
      for j in range(self.numberoflinks):
        d = d + self.D_q[k][j] * qddot[j] 
        for i in range(self.numberoflinks):
          ct = ct + c[i][j][k] * qdot[i] * qdot[j]
      T[k] = d + ct + Phi[k]

    for i in range(self.numberoflinks):
      print('T' + str(i+1) + ' = ' + str(T[i]))

# Preparing arrays of terms to accept valid input
q = []
qdot = []
qddot = []
for i in range(1000):
  q.append(sp.symbols('q' + str(i + 1)))
  qdot.append(sp.symbols('q"' + str(i + 1)))
  qddot.append(sp.symbols('q""' + str(i + 1)))

# Initializing object robot with input [numberoflinks, D_q, V_q]
robot = Robot(2, [[5, 15 * sp.cos(q[1] - q[0])], [15 * sp.cos(q[0] - q[0]), 10]], 13 * sp.sin(q[0]) + 45 * (5 * sp.sin(q[0]) + 3 * sp.sin(q[0])))
robot.derive_equations()

T1 = 5*q""1 + 15*q""2*cos(q1 - q2) + 15.0*q"1**2*sin(q1 - q2) + 30.0*q"1*q"2*sin(q1 - q2) + 15.0*q"2**2*sin(q1 - q2) + 373*cos(q1)
T2 = 20*q""1 + 15*q""2*cos(q1 - q2) + 10*q""2 + 15.0*q"1**2*sin(q1 - q2) + 30.0*q"1*q"2*sin(q1 - q2) + 15.0*q"2**2*sin(q1 - q2)


**Animation Code**

In [ ]:
import matplotlib.pyplot as plt
def animate2R(t, q1t, q2t):  # simplest animation function very similar to matlab
    x1 = np.zeros(np.size(q1t))
    x2 = np.zeros(np.size(q1t))
    y1 = np.zeros(np.size(q1t))
    y2 = np.zeros(np.size(q1t))
    for i in range(np.size(q1t)):
        plt.clf()  # clear screen
        plt.xlim([-3, 3])
        plt.ylim([-3, 3])
        # forward kinematics to get end points of both links
        x1[i] = l1 * np.cos(q1t[i])
        y1[i] = l1 * np.sin(q1t[i])
        x2[i] = x1[i] + l2 * np.cos(q2t[i])
        y2[i] = y1[i] + l2 * np.sin(q2t[i])
        plt.plot([0, x1[i]], [0, y1[i]], '-o')  # draw link1
        plt.plot([x1[i], x2[i]], [y1[i], y2[i]], '-o')  # draw link2
        plt.pause(0.0001)
    plt.show()
    


**Forward Dynamics Inertial Angles**

In [ ]:
def forwarddynamicscontrol(m1, m2, l1, l2, xd, yd, prev_state):
    # g = 0 in case of robot in horizontal plane
    g = 9.81
    q1 = prev_state[0][0]
    print("q1",q1)
    q2 = prev_state[1][0]
    print("q2",q2)
    q1dot = prev_state[2][0]
    q2dot = prev_state[3][0]
    d11 = (m1 * ((l1/2)** 2) + m2 * (l1 ** 2) + m1*(l1**2)/3)
    d12 = m2 * (l1 * (l2/2) * np.cos(q2 - q1))
    d21 = m2 * (l1 * (l2/2) * np.cos(q2 - q1))
    d22 = m2 * (l2/2 ** 2) +  m1*(l1**2)/3
    D = np.array([[d11, d12], [d21, d22]])
    C = np.array([[-m2 * l1 * (l2/2) * np.sin(q2 - q1) * ((q2dot) ** 2) ],
                  [m2 * l1 * (l2/2) * np.sin(q2 - q1) * (q1dot) ** 2]], dtype=float)
    V = np.array([[(m1*(l1/2)+m2*l1) * g * np.cos(q1)], [m2 * g * (l2/2) * np.cos(q2)]],
                 dtype=float)
    gain = np.array([[10,0],[0,10]])
    #x1,y1,x,y = forward_kinematics(np.pi/4,np.pi/4,l1,l2)
    q1d,q2d = inverse_kinematics(xd,yd,l1,l2,elbow)
    print(q1d,q2d)
    X = np.array([[q1],[q2]])
    Xd = np.array([[q1d],[q2d]])
    Qdot = np.array([[q1dot],[q2dot]])
    gain2 = np.array([[0.1,0],[0,0.1]])
    tau = C+V+np.matmul(gain,Xd-X)-0*np.matmul(gain2,Qdot)
    detinv = (1 / ((D[0][0]) * (D[1][1]) - ((D[0][1]) * (D[1][0]))))
    di11 = detinv * D[1][1]
    di12 = -1 * detinv * D[0][1]
    di21 = -1 * detinv * D[1][0]
    di22 = detinv * D[0][0]
    Dinv = np.array([[di11, di12], [di21, di22]])
    # print(Dinv)
    sum = -C - V + tau
    qddot = np.matmul(Dinv, sum)
    qdot = np.array([[q1dot], [q2dot]])
    print(qdot)
    statedot = np.row_stack([qdot, qddot])
    return statedot

Integrator 1 Runge Kutta

In [ ]:
def runge_kutta_fourth_order(f, ut, prev_state, t0, tn, h, m1, m2, l1, l2):
    X = np.zeros([prev_state.shape[0], int((tn - t0) / h) + 1])
    X[:][0] = prev_state[:][0]
    t = t0
    i = 0
    time = np.zeros([1, int((tn - t0) / h) + 1])
    time[0][0] = t0
    while t <= tn:
        xd = ut[0][i]
        yd = ut[1][i]
        # print(prev_state)
        k1 = f(m1, m2, l1, l2, xd, yd, prev_state)
        t = t + h / 2
        k2 = f(m1, m2, l1, l2, xd, yd, (prev_state + (k1 * h / 2)))
        k3 = f(m1, m2, l1, l2, xd, yd, prev_state + (k2 * h / 2))
        t = t + h / 2
        k4 = f(m1, m2, l1, l2, xd, yd, prev_state + (k3 * h))
        k = (k1 + 2 * k2 + 2 * k3 + k4) / 6
        x_new = prev_state + k * h
        # print(x_new)
        # store the result of integration for each time step as a column in X
        X[:, i] = x_new[:, 0]
        print(np.shape(x_new))
        i = i + 1
        print(np.shape(prev_state))
        prev_state = x_new

        # print("i",i)
    return X

**Jacobian Inverse 2R Fixed Angle**

In [ ]:
def jacobianinv2R(q1, q2, xdot, ydot, xddot, yddot, l1, l2):
    Xdot = np.array([[xdot], [ydot]])
    Xddot = np.array([[xddot], [yddot]])
    J = np.array([[-l1 * np.sin(q1), -l2 * np.sin(q2)], [l1 * np.cos(q1), l2 * np.cos(q2)]])
    Jinv = np.linalg.inv(J)
    RE = np.array([[0, -1], [1, 0]])
    Qdot = np.matmul(Jinv, Xdot)
    A = (Xddot - np.matmul(np.matmul(RE, J), Qdot))
    Qddot = np.matmul(Jinv, A)
    q1dot = Qdot[0]
    q2dot = Qdot[1]
    q1ddot = Qddot[0]
    q2ddot = Qddot[1]
    return q1dot, q2dot, q1ddot, q2ddot