puma articulated TYPE VERIFICATION


A= (45, 7.5, 10), (45, -7.5, 10), (25, -7.5, 10), and (25,
7.5, 10) 
ALL THE -7.5 CANBE JUST SHIFTED THE BLOCK BY 7.5 WILL RESULT IN ALL POSITIVE VALUES SO MODIFIED VALUES
A= (45, 15 , 10), B=(45,0, 10),C= (25,0 , 10), and D=(25,
15, 10) 

FIRST CALULATING INVERSE VALUES OF A= (45, 15, 10)

In [22]:
import numpy as np
import scipy


x=[0]*3;
for n in range(3):
    print("enter the endefector x,y,z in sequemce");
    x[n]=float(input());
print("enter the length of d1 ");
d1=int(input());#length of offset of first joint from ground
print("enter the length of d2 ");
d2=int(input());#length of first joint
print("enter the length of d3 ");
d3=float(input());#length of first joint
n=x[2]-d1;
m=np.sqrt(x[0]**2+x[1]**2);
theta1=np.arctan(x[1]/x[0]);
r = (m**2+n**2-d2**2-d3**2)/(2*d2*d3)
theta3 = np.arctan(np.sqrt(1-r**2)/r)
theta2 = np.arctan(n/m) - np.arctan((d3*np.sin(theta3))/(d2+d3*np.cos(theta3)))


print((180/np.pi)*theta1,(180/np.pi)*theta2,(180/np.pi)*theta3);

enter the endefector x,y,z in sequemce
45
enter the endefector x,y,z in sequemce
15
enter the endefector x,y,z in sequemce
10
enter the length of d1 
25
enter the length of d2 
25
enter the length of d3 
25
18.43494882292201 -23.28757109105913 11.478340954533666


PUMA TYPE

In [23]:
import numpy as np
import scipy



#NOW WE MOVE TOWARDS CALCULATING THE DH TABLE

         
def my_function(j):

 A[0][0]=np.cos(theta[j]);
 A[0][1]=-np.sin(theta[j])*np.cos(alpha[j]);
 A[0][2]=np.sin(theta[j])*np.sin(alpha[j]);
 A[0][3]=np.cos(theta[j])*r[j];
 A[1][0]=np.sin(theta[j]);
 A[1][1]=np.cos(theta[j])*np.cos(alpha[j]);
 A[1][2]=-np.cos(theta[j])*np.sin(alpha[j]);
 A[1][3]=np.sin(theta[j])*r[j];
 A[2][0]=0;
 A[2][1]=np.sin(alpha[j]);
 A[2][2]=np.cos(alpha[j]);
 A[2][3]=depth[j];
 A[3][0]=0;
 A[3][1]=0;
 A[3][2]=0;
 A[3][3]=1;
 return A

#TRANSFORMATION MATRIX CALCULATOR
def my_funch(c,v):
    
     
    for i in range(c,v):
        if i!=c:
            B=B@np.array(my_function(i))
          
        else:
            B=np.array(my_function(i));
            

        
    return B;
 

#NOW WE MOVE TOWARDS JACOBIAN
def JacobianCol(i,l):
    
        z=[[0],[0],[0]];
        if joint[i]==0:#implies its prizmatic so we have to calculate only Z and later append it to zero
            Zo=ZIM1(i);
            K=np.transpose(z);
            K1=np.transpose(Zo);
            RAF=np.concatenate((K1,K),axis=1);
            RAF1=np.transpose(RAF);
            return(RAF1)
        else:#implies its revolute so we have to calculate only Z and later append it to zero
            omain=Ocal(l);
            ocha=Ocal(i);
            Ofin=omain-ocha;
            zag=ZIM1(i);
            zag2=np.transpose(zag);
            Ofim=np.transpose(Ofin);
                                                           
            PAF=np.cross(zag2,Ofim);
            PAF2=np.transpose(PAF);
            
            PAF1=np.concatenate((PAF2,zag),axis=0);
            return(PAF1);
            
        
            
 



#Z(I-1) CALCULATOR
def ZIM1(k):
 zat=[[0],[0],[1]];
 
 if k==0:
     return zat;
 else:
     RA=my_funch(0,k);
     RAn1=np.delete(RA,[3],0);
     RAn2=np.delete(RAn1,[3],1);
     
     zat=[[0],[0],[1]];
     KA=np.matmul(RAn2,zat);
     return KA
     
           
   
#On calcuator
def Ocal(k):
    rat=[[0],[0],[0]];
    if k==0:
        return rat;
    else:
        RA=my_funch(0,k);
        RAn1=np.delete(RA,[3],0);
        RAn2=np.delete(RAn1,[0,1,2],1);
        
        #KA=np.matmul(RAn2,np.transpose(ma));
        
        return RAn2;

        
        
print("enter the no. of links");
l=int(input());
joint= np.array([1]*l);
depth=[0]*l;
r=[0]*l;
theta=[0]*l;
alpha=[0]*l;

A = [[0 for x in range(4)] for y in range(4)] 



print("self mode or auto press 1 for auto 0 for self");
s=int(input());
if s==0:
    for i in range(l):
        print("please  enter 1 for revolute and 0 for prismatic");
        joint[i]=int(input());
else:
    joint=[1]*l;
    
for n in range(l):
    print("enter the depth for",n+1," link");
    depth[n]=float(input());
    print("enter the aaa for",n+1," link");
    r[n]=float(input()); #r=a
    print("enter the theta for",n+1," link in degrees");
    theta[n]=(np.pi/180)*float(input());
    print("enter the alpha for",n+1,"link in degrees");
    alpha[n]=(np.pi/180)*float(input());        
    
            
     


#FINAL CONCANATE FUNCTION OF JACOBIAN
for i in range(l):
    if i==0:
        J1=JacobianCol(i,l);
    else:
        J1=np.concatenate((J1,JacobianCol(i,l)),axis=1);

print("1JACOBIAN")
print(np.round_(J1,decimals=2))


#FINAL END EFFECTOR VELOCITY CALCULATION
vel=[0]*l;
for n in range(l):
    print("enter the endeff velocity vector for x y z as follows wrt last link");
    vel[n]=float(input());
#print(pos)
       

P2=np.matmul(J1,np.transpose(vel));
print("END EFFECTOR VELOCITY VECTOR")
print(np.round_(P2,decimals=2))
 
 


# CALCULATE THE END EFFECTOR POSITION VECTOR   
       
H=np.round_(my_funch(0,l))
P=np.delete(H,[3],0);
P3=np.delete(P,[0,1,2],1);
print("END EFFECTOR POSITION VECTOR")
print(np.round_(abs(P3),decimals=2))
print(H)

# CALCULATE THE FINAL R MATRIX
N=np.round_(my_funch(0,l))
RAn4=np.delete(N,[3],0);
RAn5=np.delete(RAn4,[3],1);
print("Final R");
print(np.round_(RAn5,decimals=2));

enter the no. of links
3
self mode or auto press 1 for auto 0 for self
1
enter the depth for 1  link
25
enter the aaa for 1  link
0
enter the theta for 1  link in degrees
18.43
enter the alpha for 1 link in degrees
90
enter the depth for 2  link
0
enter the aaa for 2  link
25
enter the theta for 2  link in degrees
-21.58
enter the alpha for 2 link in degrees
0
enter the depth for 3  link
0
enter the aaa for 3  link
25
enter the theta for 3  link in degrees
11.47
enter the alpha for 3 link in degrees
0
1JACOBIAN
[[-15.13  12.89   4.16]
 [ 45.4    4.29   1.39]
 [  0.    47.86  24.61]
 [  0.     0.32   0.32]
 [  0.    -0.95  -0.95]
 [  1.     0.     0.  ]]
enter the endeff velocity vector for x y z as follows wrt last link
0
enter the endeff velocity vector for x y z as follows wrt last link
0
enter the endeff velocity vector for x y z as follows wrt last link
0
END EFFECTOR VELOCITY VECTOR
[0. 0. 0. 0. 0. 0.]
END EFFECTOR POSITION VECTOR
[[45.]
 [15.]
 [11.]]
[[ 1.  0.  0. 45.]
 [ 0.  0.

THE VERIFICATION IS COMPLETE AS SHOWN ABOVE

INVERSE VERIFICATION
B=(45,0,10)

In [24]:
import numpy as np
import scipy


x=[0]*3;
for n in range(3):
    print("enter the endefector x,y,z in sequemce");
    x[n]=float(input());
print("enter the length of d1 ");
d1=int(input());#length of offset of first joint from ground
print("enter the length of d2 ");
d2=int(input());#length of first joint
print("enter the length of d3 ");
d3=float(input());#length of first joint
n=x[2]-d1;
m=np.sqrt(x[0]**2+x[1]**2);
theta1=np.arctan(x[1]/x[0]);
r = (m**2+n**2-d2**2-d3**2)/(2*d2*d3)
theta3 = np.arctan(np.sqrt(1-r**2)/r)
theta2 = np.arctan(n/m) - np.arctan((d3*np.sin(theta3))/(d2+d3*np.cos(theta3)))


print((180/np.pi)*theta1,(180/np.pi)*theta2,(180/np.pi)*theta3);

enter the endefector x,y,z in sequemce
45
enter the endefector x,y,z in sequemce
0
enter the endefector x,y,z in sequemce
10
enter the length of d1 
25
enter the length of d2 
25
enter the length of d3 
25
0.0 -36.86989764584401 36.86989764584401


substiriting the above values

In [1]:
import numpy as np
import scipy



#NOW WE MOVE TOWARDS CALCULATING THE DH TABLE

         
def my_function(j):

 A[0][0]=np.cos(theta[j]);
 A[0][1]=-np.sin(theta[j])*np.cos(alpha[j]);
 A[0][2]=np.sin(theta[j])*np.sin(alpha[j]);
 A[0][3]=np.cos(theta[j])*r[j];
 A[1][0]=np.sin(theta[j]);
 A[1][1]=np.cos(theta[j])*np.cos(alpha[j]);
 A[1][2]=-np.cos(theta[j])*np.sin(alpha[j]);
 A[1][3]=np.sin(theta[j])*r[j];
 A[2][0]=0;
 A[2][1]=np.sin(alpha[j]);
 A[2][2]=np.cos(alpha[j]);
 A[2][3]=depth[j];
 A[3][0]=0;
 A[3][1]=0;
 A[3][2]=0;
 A[3][3]=1;
 return A

#TRANSFORMATION MATRIX CALCULATOR
def my_funch(c,v):
    
     
    for i in range(c,v):
        if i!=c:
            B=B@np.array(my_function(i))
          
        else:
            B=np.array(my_function(i));
            

        
    return B;
 

#NOW WE MOVE TOWARDS JACOBIAN
def JacobianCol(i,l):
    
        z=[[0],[0],[0]];
        if joint[i]==0:#implies its prizmatic so we have to calculate only Z and later append it to zero
            Zo=ZIM1(i);
            K=np.transpose(z);
            K1=np.transpose(Zo);
            RAF=np.concatenate((K1,K),axis=1);
            RAF1=np.transpose(RAF);
            return(RAF1)
        else:#implies its revolute so we have to calculate only Z and later append it to zero
            omain=Ocal(l);
            ocha=Ocal(i);
            Ofin=omain-ocha;
            zag=ZIM1(i);
            zag2=np.transpose(zag);
            Ofim=np.transpose(Ofin);
                                                           
            PAF=np.cross(zag2,Ofim);
            PAF2=np.transpose(PAF);
            
            PAF1=np.concatenate((PAF2,zag),axis=0);
            return(PAF1);
            
        
            
 



#Z(I-1) CALCULATOR
def ZIM1(k):
 zat=[[0],[0],[1]];
 
 if k==0:
     return zat;
 else:
     RA=my_funch(0,k);
     RAn1=np.delete(RA,[3],0);
     RAn2=np.delete(RAn1,[3],1);
     
     zat=[[0],[0],[1]];
     KA=np.matmul(RAn2,zat);
     return KA
     
           
   
#On calcuator
def Ocal(k):
    rat=[[0],[0],[0]];
    if k==0:
        return rat;
    else:
        RA=my_funch(0,k);
        RAn1=np.delete(RA,[3],0);
        RAn2=np.delete(RAn1,[0,1,2],1);
        
        #KA=np.matmul(RAn2,np.transpose(ma));
        
        return RAn2;

        
        
print("enter the no. of links");
l=int(input());
joint= np.array([1]*l);
depth=[0]*l;
r=[0]*l;
theta=[0]*l;
alpha=[0]*l;

A = [[0 for x in range(4)] for y in range(4)] 



print("self mode or auto press 1 for auto 0 for self");
s=int(input());
if s==0:
    for i in range(l):
        print("please  enter 1 for revolute and 0 for prismatic");
        joint[i]=int(input());
else:
    joint=[1]*l;
    
for n in range(l):
    print("enter the depth for",n+1," link");
    depth[n]=float(input());
    print("enter the aaa for",n+1," link");
    r[n]=float(input()); #r=a
    print("enter the theta for",n+1," link in degrees");
    theta[n]=(np.pi/180)*float(input());
    print("enter the alpha for",n+1,"link in degrees");
    alpha[n]=(np.pi/180)*float(input());        
    
            
     


#FINAL CONCANATE FUNCTION OF JACOBIAN
for i in range(l):
    if i==0:
        J1=JacobianCol(i,l);
    else:
        J1=np.concatenate((J1,JacobianCol(i,l)),axis=1);

print("1JACOBIAN")
print(np.round_(J1,decimals=2))


#FINAL END EFFECTOR VELOCITY CALCULATION
vel=[0]*l;
for n in range(l):
    print("enter the endeff velocity vector for x y z as follows wrt last link");
    vel[n]=float(input());
#print(pos)
       

P2=np.matmul(J1,np.transpose(vel));
print("END EFFECTOR VELOCITY VECTOR")
print(np.round_(P2,decimals=2))
 
 


# CALCULATE THE END EFFECTOR POSITION VECTOR   
       
H=np.round_(my_funch(0,l))
P=np.delete(H,[3],0);
P3=np.delete(P,[0,1,2],1);
print("END EFFECTOR POSITION VECTOR")
print(np.round_(abs(P3),decimals=2))
print(H)

# CALCULATE THE FINAL R MATRIX
N=np.round_(my_funch(0,l))
RAn4=np.delete(N,[3],0);
RAn5=np.delete(RAn4,[3],1);
print("Final R");
print(np.round_(RAn5,decimals=2));

enter the no. of links
3
self mode or auto press 1 for auto 0 for self
1
enter the depth for 1  link
25
enter the aaa for 1  link
0
enter the theta for 1  link in degrees
0
enter the alpha for 1 link in degrees
90
enter the depth for 2  link
0
enter the aaa for 2  link
25
enter the theta for 2  link in degrees
-36.86
enter the alpha for 2 link in degrees
0
enter the depth for 3  link
0
enter the aaa for 3  link
25
enter the theta for 3  link in degrees
36.86
enter the alpha for 3 link in degrees
0
1JACOBIAN
[[ 0. 15. -0.]
 [45.  0.  0.]
 [-0. 45. 25.]
 [ 0.  0.  0.]
 [ 0. -1. -1.]
 [ 1.  0.  0.]]
enter the endeff velocity vector for x y z as follows wrt last link
0
enter the endeff velocity vector for x y z as follows wrt last link
0
enter the endeff velocity vector for x y z as follows wrt last link
0
END EFFECTOR VELOCITY VECTOR
[0. 0. 0. 0. 0. 0.]
END EFFECTOR POSITION VECTOR
[[45.]
 [ 0.]
 [10.]]
[[ 1. -0.  0. 45.]
 [ 0.  0. -1. -0.]
 [-0.  1.  0. 10.]
 [ 0.  0.  0.  1.]]
Final R
[

THUS POINT B IS PRESENT IN WORK SPACE

VERIFICATION OF C POINT (25,0,10)

In [2]:
import numpy as np
import scipy


x=[0]*3;
for n in range(3):
    print("enter the endefector x,y,z in sequemce");
    x[n]=float(input());
print("enter the length of d1 ");
d1=int(input());#length of offset of first joint from ground
print("enter the length of d2 ");
d2=int(input());#length of first joint
print("enter the length of d3 ");
d3=float(input());#length of first joint
n=x[2]-d1;
m=np.sqrt(x[0]**2+x[1]**2);
theta1=np.arctan(x[1]/x[0]);
r = (m**2+n**2-d2**2-d3**2)/(2*d2*d3)
theta3 = np.arctan(np.sqrt(1-r**2)/r)
theta2 = np.arctan(n/m) - np.arctan((d3*np.sin(theta3))/(d2+d3*np.cos(theta3)))


print((180/np.pi)*theta1,(180/np.pi)*theta2,(180/np.pi)*theta3);

enter the endefector x,y,z in sequemce
25
enter the endefector x,y,z in sequemce
0
enter the endefector x,y,z in sequemce
10
enter the length of d1 
25
enter the length of d2 
25
enter the length of d3 
25
0.0 4.704781025455238 -71.33707511505752


In [1]:
import numpy as np
import scipy



#NOW WE MOVE TOWARDS CALCULATING THE DH TABLE

         
def my_function(j):

 A[0][0]=np.cos(theta[j]);
 A[0][1]=-np.sin(theta[j])*np.cos(alpha[j]);
 A[0][2]=np.sin(theta[j])*np.sin(alpha[j]);
 A[0][3]=np.cos(theta[j])*r[j];
 A[1][0]=np.sin(theta[j]);
 A[1][1]=np.cos(theta[j])*np.cos(alpha[j]);
 A[1][2]=-np.cos(theta[j])*np.sin(alpha[j]);
 A[1][3]=np.sin(theta[j])*r[j];
 A[2][0]=0;
 A[2][1]=np.sin(alpha[j]);
 A[2][2]=np.cos(alpha[j]);
 A[2][3]=depth[j];
 A[3][0]=0;
 A[3][1]=0;
 A[3][2]=0;
 A[3][3]=1;
 return A

#TRANSFORMATION MATRIX CALCULATOR
def my_funch(c,v):
    
     
    for i in range(c,v):
        if i!=c:
            B=B@np.array(my_function(i))
          
        else:
            B=np.array(my_function(i));
            

        
    return B;
 

#NOW WE MOVE TOWARDS JACOBIAN
def JacobianCol(i,l):
    
        z=[[0],[0],[0]];
        if joint[i]==0:#implies its prizmatic so we have to calculate only Z and later append it to zero
            Zo=ZIM1(i);
            K=np.transpose(z);
            K1=np.transpose(Zo);
            RAF=np.concatenate((K1,K),axis=1);
            RAF1=np.transpose(RAF);
            return(RAF1)
        else:#implies its revolute so we have to calculate only Z and later append it to zero
            omain=Ocal(l);
            ocha=Ocal(i);
            Ofin=omain-ocha;
            zag=ZIM1(i);
            zag2=np.transpose(zag);
            Ofim=np.transpose(Ofin);
                                                           
            PAF=np.cross(zag2,Ofim);
            PAF2=np.transpose(PAF);
            
            PAF1=np.concatenate((PAF2,zag),axis=0);
            return(PAF1);
            
        
            
 



#Z(I-1) CALCULATOR
def ZIM1(k):
 zat=[[0],[0],[1]];
 
 if k==0:
     return zat;
 else:
     RA=my_funch(0,k);
     RAn1=np.delete(RA,[3],0);
     RAn2=np.delete(RAn1,[3],1);
     
     zat=[[0],[0],[1]];
     KA=np.matmul(RAn2,zat);
     return KA
     
           
   
#On calcuator
def Ocal(k):
    rat=[[0],[0],[0]];
    if k==0:
        return rat;
    else:
        RA=my_funch(0,k);
        RAn1=np.delete(RA,[3],0);
        RAn2=np.delete(RAn1,[0,1,2],1);
        
        #KA=np.matmul(RAn2,np.transpose(ma));
        
        return RAn2;

        
        
print("enter the no. of links");
l=int(input());
joint= np.array([1]*l);
depth=[0]*l;
r=[0]*l;
theta=[0]*l;
alpha=[0]*l;

A = [[0 for x in range(4)] for y in range(4)] 



print("self mode or auto press 1 for auto 0 for self");
s=int(input());
if s==0:
    for i in range(l):
        print("please  enter 1 for revolute and 0 for prismatic");
        joint[i]=int(input());
else:
    joint=[1]*l;
    
for n in range(l):
    print("enter the depth for",n+1," link");
    depth[n]=float(input());
    print("enter the aaa for",n+1," link");
    r[n]=float(input()); #r=a
    print("enter the theta for",n+1," link in degrees");
    theta[n]=(np.pi/180)*float(input());
    print("enter the alpha for",n+1,"link in degrees");
    alpha[n]=(np.pi/180)*float(input());        
    
            
     


#FINAL CONCANATE FUNCTION OF JACOBIAN
for i in range(l):
    if i==0:
        J1=JacobianCol(i,l);
    else:
        J1=np.concatenate((J1,JacobianCol(i,l)),axis=1);

print("1JACOBIAN")
print(np.round_(J1,decimals=2))


#FINAL END EFFECTOR VELOCITY CALCULATION
vel=[0]*l;
for n in range(l):
    print("enter the endeff velocity vector for x y z as follows wrt last link");
    vel[n]=float(input());
#print(pos)
       

P2=np.matmul(J1,np.transpose(vel));
print("END EFFECTOR VELOCITY VECTOR")
print(np.round_(P2,decimals=2))
 
 


# CALCULATE THE END EFFECTOR POSITION VECTOR   
       
H=np.round_(my_funch(0,l))
P=np.delete(H,[3],0);
P3=np.delete(P,[0,1,2],1);
print("END EFFECTOR POSITION VECTOR")
print(np.round_(abs(P3),decimals=2))
print(H)

# CALCULATE THE FINAL R MATRIX
N=np.round_(my_funch(0,l))
RAn4=np.delete(N,[3],0);
RAn5=np.delete(RAn4,[3],1);
print("Final R");
print(np.round_(RAn5,decimals=2));

enter the no. of links
3
self mode or auto press 1 for auto 0 for self
1
enter the depth for 1  link
25
enter the aaa for 1  link
0
enter the theta for 1  link in degrees
0
enter the alpha for 1 link in degrees
90
enter the depth for 2  link
0
enter the aaa for 2  link
25
enter the theta for 2  link in degrees
4.704
enter the alpha for 2 link in degrees
0
enter the depth for 3  link
0
enter the aaa for 3  link
25
enter the theta for 3  link in degrees
-71.33
enter the alpha for 3 link in degrees
0
1JACOBIAN
[[ 0.   20.9  22.95]
 [34.83  0.    0.  ]
 [-0.   34.83  9.92]
 [ 0.    0.    0.  ]
 [ 0.   -1.   -1.  ]
 [ 1.    0.    0.  ]]
enter the endeff velocity vector for x y z as follows wrt last link
0
enter the endeff velocity vector for x y z as follows wrt last link
0
enter the endeff velocity vector for x y z as follows wrt last link
0
END EFFECTOR VELOCITY VECTOR
[0. 0. 0. 0. 0. 0.]
END EFFECTOR POSITION VECTOR
[[35.]
 [ 0.]
 [ 4.]]
[[ 0.  1.  0. 35.]
 [-0.  0. -1. -0.]
 [-1.  0.  0

D=(25,15,10)

In [2]:
import numpy as np
import scipy


x=[0]*3;
for n in range(3):
    print("enter the endefector x,y,z in sequemce");
    x[n]=float(input());
print("enter the length of d1 ");
d1=int(input());#length of offset of first joint from ground
print("enter the length of d2 ");
d2=int(input());#length of first joint
print("enter the length of d3 ");
d3=float(input());#length of first joint
n=x[2]-d1;
m=np.sqrt(x[0]**2+x[1]**2);
theta1=np.arctan(x[1]/x[0]);
r = (m**2+n**2-d2**2-d3**2)/(2*d2*d3)
theta3 = np.arctan(np.sqrt(1-r**2)/r)
theta2 = np.arctan(n/m) - np.arctan((d3*np.sin(theta3))/(d2+d3*np.cos(theta3)))


print((180/np.pi)*theta1,(180/np.pi)*theta2,(180/np.pi)*theta3);

enter the endefector x,y,z in sequemce
25
enter the endefector x,y,z in sequemce
15
enter the endefector x,y,z in sequemce
10
enter the length of d1 
25
enter the length of d2 
25
enter the length of d3 
25
30.96375653207352 13.750448877780292 -81.95215375268849


In [3]:
import numpy as np
import scipy



         
def my_function(j):

 A[0][0]=np.cos(theta[j]);
 A[0][1]=-np.sin(theta[j])*np.cos(alpha[j]);
 A[0][2]=np.sin(theta[j])*np.sin(alpha[j]);
 A[0][3]=np.cos(theta[j])*r[j];
 A[1][0]=np.sin(theta[j]);
 A[1][1]=np.cos(theta[j])*np.cos(alpha[j]);
 A[1][2]=-np.cos(theta[j])*np.sin(alpha[j]);
 A[1][3]=np.sin(theta[j])*r[j];
 A[2][0]=0;
 A[2][1]=np.sin(alpha[j]);
 A[2][2]=np.cos(alpha[j]);
 A[2][3]=depth[j];
 A[3][0]=0;
 A[3][1]=0;
 A[3][2]=0;
 A[3][3]=1;
 return A

#TRANSFORMATION MATRIX CALCULATOR
def my_funch(c,v):
    
     
    for i in range(c,v):
        if i!=c:
            B=B@np.array(my_function(i))
          
        else:
            B=np.array(my_function(i));
            

        
    return B;
 

#NOW WE MOVE TOWARDS JACOBIAN
def JacobianCol(i,l):
    
        z=[[0],[0],[0]];
        if joint[i]==0:#implies its prizmatic so we have to calculate only Z and later append it to zero
            Zo=ZIM1(i);
            K=np.transpose(z);
            K1=np.transpose(Zo);
            RAF=np.concatenate((K1,K),axis=1);
            RAF1=np.transpose(RAF);
            return(RAF1)
        else:#implies its revolute so we have to calculate only Z and later append it to zero
            omain=Ocal(l);
            ocha=Ocal(i);
            Ofin=omain-ocha;
            zag=ZIM1(i);
            zag2=np.transpose(zag);
            Ofim=np.transpose(Ofin);
                                                           
            PAF=np.cross(zag2,Ofim);
            PAF2=np.transpose(PAF);
            
            PAF1=np.concatenate((PAF2,zag),axis=0);
            return(PAF1);
            
        
            
 



#Z(I-1) CALCULATOR
def ZIM1(k):
 zat=[[0],[0],[1]];
 
 if k==0:
     return zat;
 else:
     RA=my_funch(0,k);
     RAn1=np.delete(RA,[3],0);
     RAn2=np.delete(RAn1,[3],1);
     
     zat=[[0],[0],[1]];
     KA=np.matmul(RAn2,zat);
     return KA
     
           
   
#On calcuator
def Ocal(k):
    rat=[[0],[0],[0]];
    if k==0:
        return rat;
    else:
        RA=my_funch(0,k);
        RAn1=np.delete(RA,[3],0);
        RAn2=np.delete(RAn1,[0,1,2],1);
        
        #KA=np.matmul(RAn2,np.transpose(ma));
        
        return RAn2;

        
        
print("enter the no. of links");
l=int(input());
joint= np.array([1]*l);
depth=[0]*l;
r=[0]*l;
theta=[0]*l;
alpha=[0]*l;

A = [[0 for x in range(4)] for y in range(4)] 



print("self mode or auto press 1 for auto 0 for self");
s=int(input());
if s==0:
    for i in range(l):
        print("please  enter 1 for revolute and 0 for prismatic");
        joint[i]=int(input());
else:
    joint=[1]*l;
    
for n in range(l):
    print("enter the depth for",n+1," link");
    depth[n]=float(input());
    print("enter the aaa for",n+1," link");
    r[n]=float(input()); #r=a
    print("enter the theta for",n+1," link in degrees");
    theta[n]=(np.pi/180)*float(input());
    print("enter the alpha for",n+1,"link in degrees");
    alpha[n]=(np.pi/180)*float(input());        
    
            
     


#FINAL CONCANATE FUNCTION OF JACOBIAN
for i in range(l):
    if i==0:
        J1=JacobianCol(i,l);
    else:
        J1=np.concatenate((J1,JacobianCol(i,l)),axis=1);

print("1JACOBIAN")
print(np.round_(J1,decimals=2))


#FINAL END EFFECTOR VELOCITY CALCULATION
vel=[0]*l;
for n in range(l):
    print("enter the endeff velocity vector for x y z as follows wrt last link");
    vel[n]=float(input());
#print(pos)
       

P2=np.matmul(J1,np.transpose(vel));
print("END EFFECTOR VELOCITY VECTOR")
print(np.round_(P2,decimals=2))
 
 


# CALCULATE THE END EFFECTOR POSITION VECTOR   
       
H=np.round_(my_funch(0,l))
P=np.delete(H,[3],0);
P3=np.delete(P,[0,1,2],1);
print("END EFFECTOR POSITION VECTOR")
print(np.round_(abs(P3),decimals=2))
print(H)

# CALCULATE THE FINAL R MATRIX
N=np.round_(my_funch(0,l))
RAn4=np.delete(N,[3],0);
RAn5=np.delete(RAn4,[3],1);
print("Final R");
print(np.round_(RAn5,decimals=2));

enter the no. of links
3
self mode or auto press 1 for auto 0 for self
1
enter the depth for 1  link
25
enter the aaa for 1  link
0
enter the theta for 1  link in degrees
30.96
enter the alpha for 1 link in degrees
90
enter the depth for 2  link
0
enter the aaa for 2  link
25
enter the theta for 2  link in degrees
13.75
enter the alpha for 2 link in degrees
0
enter the depth for 3  link
0
enter the aaa for 3  link
25
enter the theta for 3  link in degrees
-81.95
enter the alpha for 3 link in degrees
0
1JACOBIAN
[[-17.27  14.81  19.91]
 [ 28.79   8.88  11.94]
 [  0.    33.57   9.28]
 [  0.     0.51   0.51]
 [  0.    -0.86  -0.86]
 [  1.     0.     0.  ]]
enter the endeff velocity vector for x y z as follows wrt last link
0
enter the endeff velocity vector for x y z as follows wrt last link
0
enter the endeff velocity vector for x y z as follows wrt last link
0
END EFFECTOR VELOCITY VECTOR
[0. 0. 0. 0. 0. 0.]
END EFFECTOR POSITION VECTOR
[[29.]
 [17.]
 [ 8.]]
[[ 0.  1.  1. 29.]
 [ 0.  0.

THUS ALL THE ABCD CAN BE COVERED BY THE MANIPULATOR.