SCARA TYPE VERIFICATION
A= (45, 7.5, 10), (45, -7.5, 10), (25, -7.5, 10), and (25,
7.5, 10) 
ALL THE -7.5 CANBE JUST SHIFTED THE BLOCK BY 7.5 WILL RESULT IN ALL POSITIVE VALUES SO MODIFIED VALUES
A= (45, 15 , 10), B=(45,0, 10),C= (25,0 , 10), and D=(25,
15, 10) 

FIRST CALULATING INVERSE VALUES OF A= (45, 15, 10)

In [ ]:
import numpy as np
import scipy


x=[0]*3;
for n in range(3):
    print("enter the endefector x,y,z in sequemce");
    x[n]=float(input());
print("enter the length of offset ");
offset=int(input());#length of offset of first joint from ground
print("enter the length of d1 ");
d1=int(input());#length of first joint
print("enter the length of d2 ");
d2=float(input());#length of first joint
r = abs((x[0]**2+x[1]**2-d1**2-d2**2)/(2*d1*d2))
theta2 = np.arctan(np.sqrt(abs(1-r**2))/r)
theta1 = np.arctan(x[1]/x[0]) - np.arctan((d2*np.sin(theta2))/(d1+d2*np.cos(theta2)))
d3 =offset-x[2]

print((180/np.pi)*theta1,(180/np.pi)*theta2,d3);

enter the endefector x,y,z in sequemce
45
enter the endefector x,y,z in sequemce
15
enter the endefector x,y,z in sequemce
10
enter the length of offset 
25
enter the length of d1 
25
enter the length of d2 
25
3.1805546814635168e-15 36.86989764584401 15.0


Scara TYPE

In [ ]:
import numpy as np
import scipy


print("enter the length of offset ");
offset=int(input());#length of offset of first joint from ground
#NOW WE MOVE TOWARDS CALCULATING THE DH TABLE

         
def my_function(j):

 A[0][0]=np.cos(theta[j]);
 A[0][1]=-np.sin(theta[j])*np.cos(alpha[j]);
 A[0][2]=np.sin(theta[j])*np.sin(alpha[j]);
 A[0][3]=np.cos(theta[j])*r[j];
 A[1][0]=np.sin(theta[j]);
 A[1][1]=np.cos(theta[j])*np.cos(alpha[j]);
 A[1][2]=-np.cos(theta[j])*np.sin(alpha[j]);
 A[1][3]=np.sin(theta[j])*r[j];
 A[2][0]=0;
 A[2][1]=np.sin(alpha[j]);
 A[2][2]=np.cos(alpha[j]);
 A[2][3]=offset+depth[j];
 A[3][0]=0;
 A[3][1]=0;
 A[3][2]=0;
 A[3][3]=1;
 return A

#TRANSFORMATION MATRIX CALCULATOR
def my_funch(c,v):
    
     
    for i in range(c,v):
        if i!=c:
            B=B@np.array(my_function(i))
          
        else:
            B=np.array(my_function(i));
            

        
    return B;
 

#NOW WE MOVE TOWARDS JACOBIAN
def JacobianCol(i,l):
    
        z=[[0],[0],[0]];
        if joint[i]==0:#implies its prizmatic so we have to calculate only Z and later append it to zero
            Zo=ZIM1(i);
            K=np.transpose(z);
            K1=np.transpose(Zo);
            RAF=np.concatenate((K1,K),axis=1);
            RAF1=np.transpose(RAF);
            return(RAF1)
        else:#implies its revolute so we have to calculate only Z and later append it to zero
            omain=Ocal(l);
            ocha=Ocal(i);
            Ofin=omain-ocha;
            zag=ZIM1(i);
            zag2=np.transpose(zag);
            Ofim=np.transpose(Ofin);
                                                           
            PAF=np.cross(zag2,Ofim);
            PAF2=np.transpose(PAF);
            
            PAF1=np.concatenate((PAF2,zag),axis=0);
            return(PAF1);
            
        
            
 



#Z(I-1) CALCULATOR
def ZIM1(k):
 zat=[[0],[0],[1]];
 
 if k==0:
     return zat;
 else:
     RA=my_funch(0,k);
     RAn1=np.delete(RA,[3],0);
     RAn2=np.delete(RAn1,[3],1);
     
     zat=[[0],[0],[1]];
     KA=np.matmul(RAn2,zat);
     return KA
     
           
   
#On calcuator
def Ocal(k):
    rat=[[0],[0],[0]];
    if k==0:
        return rat;
    else:
        RA=my_funch(0,k);
        RAn1=np.delete(RA,[3],0);
        RAn2=np.delete(RAn1,[0,1,2],1);
        
        #KA=np.matmul(RAn2,np.transpose(ma));
        
        return RAn2;

        
        
print("enter the no. of links");
l=int(input());
joint= np.array([1]*l);
depth=[0]*l;
r=[0]*l;
theta=[0]*l;
alpha=[0]*l;

A = [[0 for x in range(4)] for y in range(4)] 



print("self mode or auto press 1 for auto 0 for self");
s=int(input());
if s==0:
    for i in range(l):
        print("please  enter 1 for revolute and 0 for prismatic");
        joint[i]=int(input());
else:
    joint=[1]*l;
    
for n in range(l):
    print("enter the depth for",n+1," link");
    depth[n]=float(input());
    print("enter the aaa for",n+1," link");
    r[n]=float(input()); #r=a
    print("enter the theta for",n+1," link in degrees");
    theta[n]=(np.pi/180)*float(input());
    print("enter the alpha for",n+1,"link in degrees");
    alpha[n]=(np.pi/180)*float(input());        
    
            
     


#FINAL CONCANATE FUNCTION OF JACOBIAN
for i in range(l):
    if i==0:
        J1=JacobianCol(i,l);
    else:
        J1=np.concatenate((J1,JacobianCol(i,l)),axis=1);

print("1JACOBIAN")
print(np.round_(J1,decimals=2))


#FINAL END EFFECTOR VELOCITY CALCULATION
vel=[0]*l;
for n in range(l):
    print("enter the endeff velocity vector for x y z as follows wrt last link");
    vel[n]=float(input());
#print(pos)
       

P2=np.matmul(J1,np.transpose(vel));
print("END EFFECTOR VELOCITY VECTOR")
print(np.round_(P2,decimals=2))
 
 


# CALCULATE THE END EFFECTOR POSITION VECTOR   
       
H=np.round_(my_funch(0,l))
P=np.delete(H,[3],0);
P3=np.delete(P,[0,1,2],1);
print("END EFFECTOR POSITION VECTOR")
print(np.round_(abs(P3),decimals=2))
print(H)

# CALCULATE THE FINAL R MATRIX
N=np.round_(my_funch(0,l))
RAn4=np.delete(N,[3],0);
RAn5=np.delete(RAn4,[3],1);
print("Final R");
print(np.round_(RAn5,decimals=2));

enter the length of offset 
25
enter the no. of links
3
self mode or auto press 1 for auto 0 for self
0
please  enter 1 for revolute and 0 for prismatic
1
please  enter 1 for revolute and 0 for prismatic
1
please  enter 1 for revolute and 0 for prismatic
0
enter the depth for 1  link
0
enter the aaa for 1  link
25
enter the theta for 1  link in degrees
0
enter the alpha for 1 link in degrees
0
enter the depth for 2  link
0
enter the aaa for 2  link
25
enter the theta for 2  link in degrees
36.866
enter the alpha for 2 link in degrees
180
enter the depth for 3  link
15
enter the aaa for 3  link
0
enter the theta for 3  link in degrees
0
enter the alpha for 3 link in degrees
0
1JACOBIAN
[[-15. -15.   0.]
 [ 45.  20.  -0.]
 [  0.   0.  -1.]
 [  0.   0.   0.]
 [  0.   0.   0.]
 [  1.   1.   0.]]
enter the endeff velocity vector for x y z as follows wrt last link
0
enter the endeff velocity vector for x y z as follows wrt last link
0
enter the endeff velocity vector for x y z as follows wrt

THE VERIFICATION IS COMPLETE AS SHOWN ABOVE

INVERSE VERIFICATION
B=(45,0,10)

In [ ]:
import numpy as np
import scipy


x=[0]*3;
for n in range(3):
    print("enter the endefector x,y,z in sequemce");
    x[n]=float(input());
print("enter the length of offset ");
offset=int(input());#length of offset of first joint from ground
print("enter the length of d1 ");
d1=int(input());#length of first joint
print("enter the length of d2 ");
d2=float(input());#length of first joint
r = abs((x[0]**2+x[1]**2-d1**2-d2**2)/(2*d1*d2))
theta2 = np.arctan(np.sqrt(abs(1-r**2))/r)
theta1 = np.arctan(x[1]/x[0]) - np.arctan((d2*np.sin(theta2))/(d1+d2*np.cos(theta2)))
d3 =offset-x[2]

print((180/np.pi)*theta1,(180/np.pi)*theta2,d3);

enter the endefector x,y,z in sequemce
45
enter the endefector x,y,z in sequemce
0
enter the endefector x,y,z in sequemce
10
enter the length of offset 
25
enter the length of d1 
25
enter the length of d2 
25
-25.841932763167126 51.68386552633426 15.0


substiriting the above values

In [ ]:
import numpy as np
import scipy


print("enter the length of offset ");
offset=int(input());#length of offset of first joint from ground
#NOW WE MOVE TOWARDS CALCULATING THE DH TABLE

         
def my_function(j):

 A[0][0]=np.cos(theta[j]);
 A[0][1]=-np.sin(theta[j])*np.cos(alpha[j]);
 A[0][2]=np.sin(theta[j])*np.sin(alpha[j]);
 A[0][3]=np.cos(theta[j])*r[j];
 A[1][0]=np.sin(theta[j]);
 A[1][1]=np.cos(theta[j])*np.cos(alpha[j]);
 A[1][2]=-np.cos(theta[j])*np.sin(alpha[j]);
 A[1][3]=np.sin(theta[j])*r[j];
 A[2][0]=0;
 A[2][1]=np.sin(alpha[j]);
 A[2][2]=np.cos(alpha[j]);
 A[2][3]=offset+depth[j];
 A[3][0]=0;
 A[3][1]=0;
 A[3][2]=0;
 A[3][3]=1;
 return A

#TRANSFORMATION MATRIX CALCULATOR
def my_funch(c,v):
    
     
    for i in range(c,v):
        if i!=c:
            B=B@np.array(my_function(i))
          
        else:
            B=np.array(my_function(i));
            

        
    return B;
 

#NOW WE MOVE TOWARDS JACOBIAN
def JacobianCol(i,l):
    
        z=[[0],[0],[0]];
        if joint[i]==0:#implies its prizmatic so we have to calculate only Z and later append it to zero
            Zo=ZIM1(i);
            K=np.transpose(z);
            K1=np.transpose(Zo);
            RAF=np.concatenate((K1,K),axis=1);
            RAF1=np.transpose(RAF);
            return(RAF1)
        else:#implies its revolute so we have to calculate only Z and later append it to zero
            omain=Ocal(l);
            ocha=Ocal(i);
            Ofin=omain-ocha;
            zag=ZIM1(i);
            zag2=np.transpose(zag);
            Ofim=np.transpose(Ofin);
                                                           
            PAF=np.cross(zag2,Ofim);
            PAF2=np.transpose(PAF);
            
            PAF1=np.concatenate((PAF2,zag),axis=0);
            return(PAF1);
            
        
            
 



#Z(I-1) CALCULATOR
def ZIM1(k):
 zat=[[0],[0],[1]];
 
 if k==0:
     return zat;
 else:
     RA=my_funch(0,k);
     RAn1=np.delete(RA,[3],0);
     RAn2=np.delete(RAn1,[3],1);
     
     zat=[[0],[0],[1]];
     KA=np.matmul(RAn2,zat);
     return KA
     
           
   
#On calcuator
def Ocal(k):
    rat=[[0],[0],[0]];
    if k==0:
        return rat;
    else:
        RA=my_funch(0,k);
        RAn1=np.delete(RA,[3],0);
        RAn2=np.delete(RAn1,[0,1,2],1);
        
        #KA=np.matmul(RAn2,np.transpose(ma));
        
        return RAn2;

        
        
print("enter the no. of links");
l=int(input());
joint= np.array([1]*l);
depth=[0]*l;
r=[0]*l;
theta=[0]*l;
alpha=[0]*l;

A = [[0 for x in range(4)] for y in range(4)] 



print("self mode or auto press 1 for auto 0 for self");
s=int(input());
if s==0:
    for i in range(l):
        print("please  enter 1 for revolute and 0 for prismatic");
        joint[i]=int(input());
else:
    joint=[1]*l;
    
for n in range(l):
    print("enter the depth for",n+1," link");
    depth[n]=float(input());
    print("enter the aaa for",n+1," link");
    r[n]=float(input()); #r=a
    print("enter the theta for",n+1," link in degrees");
    theta[n]=(np.pi/180)*float(input());
    print("enter the alpha for",n+1,"link in degrees");
    alpha[n]=(np.pi/180)*float(input());        
    
            
     


#FINAL CONCANATE FUNCTION OF JACOBIAN
for i in range(l):
    if i==0:
        J1=JacobianCol(i,l);
    else:
        J1=np.concatenate((J1,JacobianCol(i,l)),axis=1);

print("1JACOBIAN")
print(np.round_(J1,decimals=2))


#FINAL END EFFECTOR VELOCITY CALCULATION
vel=[0]*l;
for n in range(l):
    print("enter the endeff velocity vector for x y z as follows wrt last link");
    vel[n]=float(input());
#print(pos)
       

P2=np.matmul(J1,np.transpose(vel));
print("END EFFECTOR VELOCITY VECTOR")
print(np.round_(P2,decimals=2))
 
 


# CALCULATE THE END EFFECTOR POSITION VECTOR   
       
H=np.round_(my_funch(0,l))
P=np.delete(H,[3],0);
P3=np.delete(P,[0,1,2],1);
print("END EFFECTOR POSITION VECTOR")
print(np.round_(abs(P3),decimals=2))
print(H)

# CALCULATE THE FINAL R MATRIX
N=np.round_(my_funch(0,l))
RAn4=np.delete(N,[3],0);
RAn5=np.delete(RAn4,[3],1);
print("Final R");
print(np.round_(RAn5,decimals=2));

enter the length of offset 
25
enter the no. of links
3
self mode or auto press 1 for auto 0 for self
0
please  enter 1 for revolute and 0 for prismatic
1
please  enter 1 for revolute and 0 for prismatic
1
please  enter 1 for revolute and 0 for prismatic
0
enter the depth for 1  link
0
enter the aaa for 1  link
25
enter the theta for 1  link in degrees
-25.84
enter the alpha for 1 link in degrees
0
enter the depth for 2  link
0
enter the aaa for 2  link
25
enter the theta for 2  link in degrees
51.68
enter the alpha for 2 link in degrees
180
enter the depth for 3  link
15
enter the aaa for 3  link
0
enter the theta for 3  link in degrees
0
enter the alpha for 3 link in degrees
0
1JACOBIAN
[[  0.  -10.9   0. ]
 [ 45.   22.5  -0. ]
 [ -0.    0.   -1. ]
 [  0.    0.    0. ]
 [  0.    0.    0. ]
 [  1.    1.    0. ]]
enter the endeff velocity vector for x y z as follows wrt last link
0
enter the endeff velocity vector for x y z as follows wrt last link
0
enter the endeff velocity vector fo

THUS POINT B IS PRESENT IN WORK SPACE

VERIFICATION OF C POINT (25,0,10)

In [12]:
import numpy as np
import scipy


x=[0]*3;
for n in range(3):
    print("enter the endefector x,y,z in sequemce");
    x[n]=float(input());
print("enter the length of offset ");
offset=int(input());#length of offset of first joint from ground
print("enter the length of d1 ");
d1=int(input());#length of first joint
print("enter the length of d2 ");
d2=float(input());#length of first joint
r = (x[0]**2+x[1]**2-d1**2-d2**2)/(2*d1*d2)
theta2 = np.arctan(np.sqrt(1-r**2)/r)
theta1 = np.arctan(x[1]/x[0]) - np.arctan((d2*np.sin(theta2))/(d1+d2*np.cos(theta2)))
d3 =offset-x[2]

print((180/np.pi)*theta1,(180/np.pi)*theta2,d3);

enter the endefector x,y,z in sequemce
25
enter the endefector x,y,z in sequemce
0
enter the endefector x,y,z in sequemce
10
enter the length of offset 
25
enter the length of d1 
25
enter the length of d2 
25
29.999999999999996 -59.99999999999999 15.0


In [13]:
import numpy as np
import scipy


print("enter the length of offset ");
offset=int(input());#length of offset of first joint from ground
#NOW WE MOVE TOWARDS CALCULATING THE DH TABLE

         
def my_function(j):

 A[0][0]=np.cos(theta[j]);
 A[0][1]=-np.sin(theta[j])*np.cos(alpha[j]);
 A[0][2]=np.sin(theta[j])*np.sin(alpha[j]);
 A[0][3]=np.cos(theta[j])*r[j];
 A[1][0]=np.sin(theta[j]);
 A[1][1]=np.cos(theta[j])*np.cos(alpha[j]);
 A[1][2]=-np.cos(theta[j])*np.sin(alpha[j]);
 A[1][3]=np.sin(theta[j])*r[j];
 A[2][0]=0;
 A[2][1]=np.sin(alpha[j]);
 A[2][2]=np.cos(alpha[j]);
 A[2][3]=offset+depth[j];
 A[3][0]=0;
 A[3][1]=0;
 A[3][2]=0;
 A[3][3]=1;
 return A

#TRANSFORMATION MATRIX CALCULATOR
def my_funch(c,v):
    
     
    for i in range(c,v):
        if i!=c:
            B=B@np.array(my_function(i))
          
        else:
            B=np.array(my_function(i));
            

        
    return B;
 

#NOW WE MOVE TOWARDS JACOBIAN
def JacobianCol(i,l):
    
        z=[[0],[0],[0]];
        if joint[i]==0:#implies its prizmatic so we have to calculate only Z and later append it to zero
            Zo=ZIM1(i);
            K=np.transpose(z);
            K1=np.transpose(Zo);
            RAF=np.concatenate((K1,K),axis=1);
            RAF1=np.transpose(RAF);
            return(RAF1)
        else:#implies its revolute so we have to calculate only Z and later append it to zero
            omain=Ocal(l);
            ocha=Ocal(i);
            Ofin=omain-ocha;
            zag=ZIM1(i);
            zag2=np.transpose(zag);
            Ofim=np.transpose(Ofin);
                                                           
            PAF=np.cross(zag2,Ofim);
            PAF2=np.transpose(PAF);
            
            PAF1=np.concatenate((PAF2,zag),axis=0);
            return(PAF1);
            
        
            
 



#Z(I-1) CALCULATOR
def ZIM1(k):
 zat=[[0],[0],[1]];
 
 if k==0:
     return zat;
 else:
     RA=my_funch(0,k);
     RAn1=np.delete(RA,[3],0);
     RAn2=np.delete(RAn1,[3],1);
     
     zat=[[0],[0],[1]];
     KA=np.matmul(RAn2,zat);
     return KA
     
           
   
#On calcuator
def Ocal(k):
    rat=[[0],[0],[0]];
    if k==0:
        return rat;
    else:
        RA=my_funch(0,k);
        RAn1=np.delete(RA,[3],0);
        RAn2=np.delete(RAn1,[0,1,2],1);
        
        #KA=np.matmul(RAn2,np.transpose(ma));
        
        return RAn2;

        
        
print("enter the no. of links");
l=int(input());
joint= np.array([1]*l);
depth=[0]*l;
r=[0]*l;
theta=[0]*l;
alpha=[0]*l;

A = [[0 for x in range(4)] for y in range(4)] 



print("self mode or auto press 1 for auto 0 for self");
s=int(input());
if s==0:
    for i in range(l):
        print("please  enter 1 for revolute and 0 for prismatic");
        joint[i]=int(input());
else:
    joint=[1]*l;
    
for n in range(l):
    print("enter the depth for",n+1," link");
    depth[n]=float(input());
    print("enter the aaa for",n+1," link");
    r[n]=float(input()); #r=a
    print("enter the theta for",n+1," link in degrees");
    theta[n]=(np.pi/180)*float(input());
    print("enter the alpha for",n+1,"link in degrees");
    alpha[n]=(np.pi/180)*float(input());        
    
            
     


#FINAL CONCANATE FUNCTION OF JACOBIAN
for i in range(l):
    if i==0:
        J1=JacobianCol(i,l);
    else:
        J1=np.concatenate((J1,JacobianCol(i,l)),axis=1);

print("1JACOBIAN")
print(np.round_(J1,decimals=2))


#FINAL END EFFECTOR VELOCITY CALCULATION
vel=[0]*l;
for n in range(l):
    print("enter the endeff velocity vector for x y z as follows wrt last link");
    vel[n]=float(input());
#print(pos)
       

P2=np.matmul(J1,np.transpose(vel));
print("END EFFECTOR VELOCITY VECTOR")
print(np.round_(P2,decimals=2))
 
 


# CALCULATE THE END EFFECTOR POSITION VECTOR   
       
H=np.round_(my_funch(0,l))
P=np.delete(H,[3],0);
P3=np.delete(P,[0,1,2],1);
print("END EFFECTOR POSITION VECTOR")
print(np.round_(abs(P3),decimals=2))
print(H)

# CALCULATE THE FINAL R MATRIX
N=np.round_(my_funch(0,l))
RAn4=np.delete(N,[3],0);
RAn5=np.delete(RAn4,[3],1);
print("Final R");
print(np.round_(RAn5,decimals=2));

enter the length of offset 
25
enter the no. of links
3
self mode or auto press 1 for auto 0 for self
0
please  enter 1 for revolute and 0 for prismatic
1
please  enter 1 for revolute and 0 for prismatic
1
please  enter 1 for revolute and 0 for prismatic
0
enter the depth for 1  link
0
enter the aaa for 1  link
25
enter the theta for 1  link in degrees
30
enter the alpha for 1 link in degrees
0
enter the depth for 2  link
0
enter the aaa for 2  link
25
enter the theta for 2  link in degrees
-60
enter the alpha for 2 link in degrees
180
enter the depth for 3  link
15
enter the aaa for 3  link
0
enter the theta for 3  link in degrees
0
enter the alpha for 3 link in degrees
0
1JACOBIAN
[[ 0.   12.5  -0.  ]
 [43.3  21.65 -0.  ]
 [-0.   -0.   -1.  ]
 [ 0.    0.    0.  ]
 [ 0.    0.    0.  ]
 [ 1.    1.    0.  ]]
enter the endeff velocity vector for x y z as follows wrt last link
0
enter the endeff velocity vector for x y z as follows wrt last link
0
enter the endeff velocity vector for x y 

D=(25,15,10)

In [14]:
import numpy as np
import scipy


x=[0]*3;
for n in range(3):
    print("enter the endefector x,y,z in sequemce");
    x[n]=float(input());
print("enter the length of offset ");
offset=int(input());#length of offset of first joint from ground
print("enter the length of d1 ");
d1=int(input());#length of first joint
print("enter the length of d2 ");
d2=float(input());#length of first joint
r = (x[0]**2+x[1]**2-d1**2-d2**2)/(2*d1*d2)
theta2 = np.arctan(np.sqrt(abs(1-r**2))/r)
theta1 = np.arctan(x[1]/x[0]) - np.arctan((d2*np.sin(theta2))/(d1+d2*np.cos(theta2)))
d3 =offset-x[2]

print((180/np.pi)*theta1,(180/np.pi)*theta2,d3);

enter the endefector x,y,z in sequemce
25
enter the endefector x,y,z in sequemce
15
enter the endefector x,y,z in sequemce
10
enter the length of offset 
25
enter the length of d1 
25
enter the length of d2 
25
66.63229408960228 -71.33707511505752 15.0


In [16]:
import numpy as np
import scipy


print("enter the length of offset ");
offset=int(input());#length of offset of first joint from ground
#NOW WE MOVE TOWARDS CALCULATING THE DH TABLE

         
def my_function(j):

 A[0][0]=np.cos(theta[j]);
 A[0][1]=-np.sin(theta[j])*np.cos(alpha[j]);
 A[0][2]=np.sin(theta[j])*np.sin(alpha[j]);
 A[0][3]=np.cos(theta[j])*r[j];
 A[1][0]=np.sin(theta[j]);
 A[1][1]=np.cos(theta[j])*np.cos(alpha[j]);
 A[1][2]=-np.cos(theta[j])*np.sin(alpha[j]);
 A[1][3]=np.sin(theta[j])*r[j];
 A[2][0]=0;
 A[2][1]=np.sin(alpha[j]);
 A[2][2]=np.cos(alpha[j]);
 A[2][3]=offset+depth[j];
 A[3][0]=0;
 A[3][1]=0;
 A[3][2]=0;
 A[3][3]=1;
 return A

#TRANSFORMATION MATRIX CALCULATOR
def my_funch(c,v):
    
     
    for i in range(c,v):
        if i!=c:
            B=B@np.array(my_function(i))
          
        else:
            B=np.array(my_function(i));
            

        
    return B;
 

#NOW WE MOVE TOWARDS JACOBIAN
def JacobianCol(i,l):
    
        z=[[0],[0],[0]];
        if joint[i]==0:#implies its prizmatic so we have to calculate only Z and later append it to zero
            Zo=ZIM1(i);
            K=np.transpose(z);
            K1=np.transpose(Zo);
            RAF=np.concatenate((K1,K),axis=1);
            RAF1=np.transpose(RAF);
            return(RAF1)
        else:#implies its revolute so we have to calculate only Z and later append it to zero
            omain=Ocal(l);
            ocha=Ocal(i);
            Ofin=omain-ocha;
            zag=ZIM1(i);
            zag2=np.transpose(zag);
            Ofim=np.transpose(Ofin);
                                                           
            PAF=np.cross(zag2,Ofim);
            PAF2=np.transpose(PAF);
            
            PAF1=np.concatenate((PAF2,zag),axis=0);
            return(PAF1);
            
        
            
 



#Z(I-1) CALCULATOR
def ZIM1(k):
 zat=[[0],[0],[1]];
 
 if k==0:
     return zat;
 else:
     RA=my_funch(0,k);
     RAn1=np.delete(RA,[3],0);
     RAn2=np.delete(RAn1,[3],1);
     
     zat=[[0],[0],[1]];
     KA=np.matmul(RAn2,zat);
     return KA
     
           
   
#On calcuator
def Ocal(k):
    rat=[[0],[0],[0]];
    if k==0:
        return rat;
    else:
        RA=my_funch(0,k);
        RAn1=np.delete(RA,[3],0);
        RAn2=np.delete(RAn1,[0,1,2],1);
        
        #KA=np.matmul(RAn2,np.transpose(ma));
        
        return RAn2;

        
        
print("enter the no. of links");
l=int(input());
joint= np.array([1]*l);
depth=[0]*l;
r=[0]*l;
theta=[0]*l;
alpha=[0]*l;

A = [[0 for x in range(4)] for y in range(4)] 



print("self mode or auto press 1 for auto 0 for self");
s=int(input());
if s==0:
    for i in range(l):
        print("please  enter 1 for revolute and 0 for prismatic");
        joint[i]=int(input());
else:
    joint=[1]*l;
    
for n in range(l):
    print("enter the depth for",n+1," link");
    depth[n]=float(input());
    print("enter the aaa for",n+1," link");
    r[n]=float(input()); #r=a
    print("enter the theta for",n+1," link in degrees");
    theta[n]=(np.pi/180)*float(input());
    print("enter the alpha for",n+1,"link in degrees");
    alpha[n]=(np.pi/180)*float(input());        
    
            
     


#FINAL CONCANATE FUNCTION OF JACOBIAN
for i in range(l):
    if i==0:
        J1=JacobianCol(i,l);
    else:
        J1=np.concatenate((J1,JacobianCol(i,l)),axis=1);

print("1JACOBIAN")
print(np.round_(J1,decimals=2))


#FINAL END EFFECTOR VELOCITY CALCULATION
vel=[0]*l;
for n in range(l):
    print("enter the endeff velocity vector for x y z as follows wrt last link");
    vel[n]=float(input());
#print(pos)
       

P2=np.matmul(J1,np.transpose(vel));
print("END EFFECTOR VELOCITY VECTOR")
print(np.round_(P2,decimals=2))
 
 


# CALCULATE THE END EFFECTOR POSITION VECTOR   
       
H=np.round_(my_funch(0,l))
P=np.delete(H,[3],0);
P3=np.delete(P,[0,1,2],1);
print("END EFFECTOR POSITION VECTOR")
print(np.round_(abs(P3),decimals=2))
print(H)

# CALCULATE THE FINAL R MATRIX
N=np.round_(my_funch(0,l))
RAn4=np.delete(N,[3],0);
RAn5=np.delete(RAn4,[3],1);
print("Final R");
print(np.round_(RAn5,decimals=2));

enter the length of offset 
25
enter the no. of links
3
self mode or auto press 1 for auto 0 for self
0
please  enter 1 for revolute and 0 for prismatic
1
please  enter 1 for revolute and 0 for prismatic
1
please  enter 1 for revolute and 0 for prismatic
0
enter the depth for 1  link
0
enter the aaa for 1  link
25
enter the theta for 1  link in degrees
66.63
enter the alpha for 1 link in degrees
0
enter the depth for 2  link
0
enter the aaa for 2  link
25
enter the theta for 2  link in degrees
-71.33
enter the alpha for 2 link in degrees
180
enter the depth for 3  link
15
enter the aaa for 3  link
0
enter the theta for 3  link in degrees
0
enter the alpha for 3 link in degrees
0
1JACOBIAN
[[-20.9    2.05  -0.  ]
 [ 34.83  24.92  -0.  ]
 [  0.    -0.    -1.  ]
 [  0.     0.     0.  ]
 [  0.     0.     0.  ]
 [  1.     1.     0.  ]]
enter the endeff velocity vector for x y z as follows wrt last link
0
enter the endeff velocity vector for x y z as follows wrt last link
0
enter the endeff 

THUS ALL THE ABCD CAN BE COVERED BY THE MANIPULATORWITH THE D3 MUST BE 25 CM MININUM